server.addr=:8080
app.store=postgres
queue.store=redis
postgres.dsn=postgres://user:pass@localhost:5432/buy_ticket_prod?sslmode=disable
postgres.pool.maxIdleConns=10
postgres.pool.maxOpenConns=50
postgres.connMaxIdleTime=30m
postgres.connMaxLifetime=2h
redis.addr=localhost:6379
redis.db=0
redis.password=
order.payment.ttl_minutes=10
payment.mock.merchant_id=
payment.mock.hash_key=
payment.mock.hash_iv=
payment.mock.base_url=
payment.mock.callback_url=
payment.mock.timeout_seconds=3
