app.store=postgres
postgres.dsn=postgres://user:pass@localhost:5432/buy_ticket_prod?sslmode=disable
postgres.pool.maxIdleConns=10
postgres.pool.maxOpenConns=50
postgres.connMaxIdleTime=30m
postgres.connMaxLifetime=2h
