<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import Button from 'primevue/button'
import Tag from 'primevue/tag'

import StateBanner from '../components/StateBanner.vue'
import AppShell from '../layouts/AppShell.vue'
import { useBookingFlowStore } from '../stores/bookingFlow'

const route = useRoute()
const router = useRouter()
const flow = useBookingFlowStore()

const eventId = computed(() => Number(route.params.eventId))
const holdMinutes = ref(10)
const orderNo = ref(`ORD-${Date.now()}`)
const selectedSection = computed(
  () => flow.sections.find((section) => section.id === flow.reservation?.section_id) ?? null,
)

function formatDateTime(value?: string) {
  if (!value) return '-'
  return new Date(value).toLocaleString('zh-TW', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  })
}

function formatCurrency(value?: number) {
  return new Intl.NumberFormat('zh-TW', {
    style: 'currency',
    currency: 'TWD',
    maximumFractionDigits: 0,
  }).format(value ?? 0)
}

async function createOrder() {
  try {
    await flow.createOrderAction({
      orderNo: orderNo.value,
      holdMinutes: holdMinutes.value,
    })
    if (flow.order) {
      router.push(`/events/${eventId.value}/order`)
    }
  } catch {}
}

async function chooseAgain() {
  try {
    await flow.cancelReservationAction()
    await flow.loadEventBundle(eventId.value)
    router.push(`/events/${eventId.value}/tickets`)
  } catch {}
}
</script>

<template>
  <AppShell>
    <StateBanner
      :loading="flow.isPending('createOrder') || flow.isPending('cancelReservation')"
      :error="flow.getError('createOrder') || flow.getError('cancelReservation')"
      loading-text="Processing reservation..."
      :retryable="true"
      @retry="createOrder"
    />

    <section class="flow-page">
      <div class="detail-heading">
        <span></span>
        <h1>Reservation Review</h1>
        <span></span>
      </div>

      <div v-if="!flow.reservation" class="empty-panel">
        <p>No reservation found. Select tickets again to create a temporary hold.</p>
        <Button label="Back to Seats" severity="danger" @click="router.push(`/events/${eventId}/tickets`)" />
      </div>

      <div v-else class="flow-layout">
        <section class="summary-card">
          <h2>Ticket Confirmation</h2>
          <div class="status-list">
            <div>
              <span>Event</span>
              <strong>{{ flow.currentEvent?.name ?? '-' }}</strong>
            </div>
            <div>
              <span>Section</span>
              <strong>{{ selectedSection?.name ?? flow.reservation.section_id }}</strong>
            </div>
            <div>
              <span>Reservation ID</span>
              <strong>{{ flow.reservation.id }}</strong>
            </div>
            <div>
              <span>Status</span>
              <Tag :value="String(flow.reservation.status)" severity="info" />
            </div>
            <div>
              <span>Quantity</span>
              <strong>{{ flow.reservation.quantity }}</strong>
            </div>
            <div>
              <span>Unit Price</span>
              <strong>{{ formatCurrency(flow.reservation.unit_price) }}</strong>
            </div>
            <div>
              <span>Total</span>
              <strong>{{ formatCurrency(flow.reservation.total_amount) }}</strong>
            </div>
            <div>
              <span>Expires At</span>
              <strong>{{ formatDateTime(flow.reservation.expires_at) }}</strong>
            </div>
          </div>
        </section>

        <aside class="action-panel">
          <h2>Submit Order</h2>
          <p>
            Review the selected tickets before submitting. Order number is generated by the frontend for
            this demo and cannot be edited here.
          </p>
          <div class="readonly-field">
            <span>Order No</span>
            <strong class="mono">{{ orderNo }}</strong>
          </div>
          <Button
            label="Submit Order"
            severity="danger"
            :loading="flow.isPending('createOrder')"
            @click="createOrder"
          />
          <Button
            label="Choose Again"
            severity="secondary"
            :loading="flow.isPending('cancelReservation')"
            @click="chooseAgain"
          />
        </aside>
      </div>
    </section>
  </AppShell>
</template>
