CREATE TABLE idempotency_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(255) NOT NULL,
    user_id BIGINT NULL,
    endpoint VARCHAR(100) NOT NULL,
    request_hash VARCHAR(128) NOT NULL,
    status SMALLINT NOT NULL,
    response_status INTEGER NULL,
    response_body JSONB NULL,
    locked_until TIMESTAMPTZ NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_idempotency_keys_key_endpoint
ON idempotency_keys (key, endpoint);

CREATE INDEX idx_idempotency_keys_expires_at
ON idempotency_keys (expires_at);
