CREATE TABLE payment_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    payment_id BIGINT NULL,
    idempotency_key VARCHAR(255) NULL,
    provider VARCHAR(50) NOT NULL,
    merchant_trade_no VARCHAR(80) NOT NULL,
    provider_trade_no VARCHAR(80) NULL,
    method VARCHAR(50) NOT NULL,
    amount BIGINT NOT NULL,
    status SMALLINT NOT NULL,
    request_payload JSONB NULL,
    response_payload JSONB NULL,
    callback_payload JSONB NULL,
    failure_reason TEXT NULL,
    expires_at TIMESTAMPTZ NULL,
    succeeded_at TIMESTAMPTZ NULL,
    failed_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (amount >= 0)
);

CREATE UNIQUE INDEX idx_payment_attempts_merchant_trade_no
ON payment_attempts (merchant_trade_no);

CREATE INDEX idx_payment_attempts_order_id_status_created_at
ON payment_attempts (order_id, status, created_at DESC);

CREATE UNIQUE INDEX idx_payment_attempts_idempotency_key
ON payment_attempts (idempotency_key)
WHERE idempotency_key IS NOT NULL;

CREATE INDEX idx_payment_attempts_provider_trade_no
ON payment_attempts (provider, provider_trade_no)
WHERE provider_trade_no IS NOT NULL;
