ALTER TABLE organizers
ADD COLUMN version BIGINT NOT NULL DEFAULT 1;

ALTER TABLE admin_users
ADD COLUMN version BIGINT NOT NULL DEFAULT 1;

ALTER TABLE events
ADD COLUMN version BIGINT NOT NULL DEFAULT 1;

ALTER TABLE event_sections
ADD COLUMN version BIGINT NOT NULL DEFAULT 1;
