CREATE TABLE outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(80) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    payload JSONB NOT NULL,
    status SMALLINT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,
    next_attempt_at TIMESTAMPTZ NULL,
    last_error TEXT NULL,
    published_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (attempts >= 0),
    CHECK (max_attempts > 0)
);

CREATE UNIQUE INDEX idx_outbox_events_event_id
ON outbox_events (event_id);

CREATE INDEX idx_outbox_events_pending
ON outbox_events (status, next_attempt_at, created_at, id)
WHERE status = 1;

CREATE INDEX idx_outbox_events_aggregate
ON outbox_events (aggregate_type, aggregate_id, created_at DESC);
