CREATE TABLE organizers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    status SMALLINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_organizers_status ON organizers (status);

ALTER TABLE events
ADD COLUMN organizer_id BIGINT NULL;

CREATE INDEX idx_events_organizer_id_status ON events (organizer_id, status);

INSERT INTO organizers (
    id,
    name,
    status
) VALUES (
    1,
    'Default Organizer',
    1
);

UPDATE events
SET organizer_id = 1
WHERE organizer_id IS NULL;

ALTER TABLE events
ALTER COLUMN organizer_id SET NOT NULL;

ALTER TABLE events
ADD CONSTRAINT fk_events_organizer_id
FOREIGN KEY (organizer_id) REFERENCES organizers(id);

SELECT setval(pg_get_serial_sequence('organizers', 'id'), COALESCE((SELECT MAX(id) FROM organizers), 1), true);

CREATE TABLE admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id BIGINT NULL REFERENCES organizers(id),
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    status SMALLINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (role IN ('SUPER_ADMIN', 'EVENT_ADMIN'))
);

CREATE UNIQUE INDEX idx_admin_users_email ON admin_users (email);
CREATE INDEX idx_admin_users_organizer_id_status ON admin_users (organizer_id, status);

INSERT INTO admin_users (
    id,
    organizer_id,
    name,
    email,
    password_hash,
    role,
    status
) VALUES (
    1,
    NULL,
    'Super Admin',
    'admin@example.com',
    '$2a$10$C98Lze8JLKbSUnfmKjJ9VeKsmGNw4q71gUA53CSVEJHrpYJcGQG3G',
    'SUPER_ADMIN',
    1
);

SELECT setval(pg_get_serial_sequence('admin_users', 'id'), COALESCE((SELECT MAX(id) FROM admin_users), 1), true);

CREATE TABLE admin_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT NOT NULL REFERENCES admin_users(id),
    action VARCHAR(100) NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    target_id BIGINT NOT NULL,
    reason TEXT NULL,
    ip_address VARCHAR(64) NULL,
    user_agent TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_admin_audit_logs_admin_user_id_created_at
ON admin_audit_logs (admin_user_id, created_at DESC, id DESC);

CREATE INDEX idx_admin_audit_logs_target_created_at
ON admin_audit_logs (target_type, target_id, created_at DESC, id DESC);
