// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_audit_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminAuditLog = `-- name: CreateAdminAuditLog :one
INSERT INTO admin_audit_logs (
    admin_user_id,
    action,
    target_type,
    target_id,
    reason,
    ip_address,
    user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING
    id,
    admin_user_id,
    action,
    target_type,
    target_id,
    reason,
    ip_address,
    user_agent,
    created_at
`

type CreateAdminAuditLogParams struct {
	AdminUserID int64       `json:"admin_user_id"`
	Action      string      `json:"action"`
	TargetType  string      `json:"target_type"`
	TargetID    int64       `json:"target_id"`
	Reason      pgtype.Text `json:"reason"`
	IpAddress   pgtype.Text `json:"ip_address"`
	UserAgent   pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateAdminAuditLog(ctx context.Context, arg CreateAdminAuditLogParams) (AdminAuditLog, error) {
	row := q.db.QueryRow(ctx, createAdminAuditLog,
		arg.AdminUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Reason,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AdminAuditLog
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminAuditLogs = `-- name: ListAdminAuditLogs :many
SELECT
    l.id,
    l.admin_user_id,
    au.name AS admin_user_name,
    au.email AS admin_user_email,
    au.role AS admin_user_role,
    au.status AS admin_user_status,
    l.action,
    l.target_type,
    l.target_id,
    CASE
        WHEN l.target_type = 'ADMIN_USER' THEN target_admin.name
        WHEN l.target_type = 'ORGANIZER' THEN target_organizer.name
        WHEN l.target_type = 'EVENT' THEN target_event.name
        WHEN l.target_type = 'SECTION' THEN target_section.section_name
        WHEN l.target_type = 'ORDER' THEN target_order.order_no
        ELSE NULL
    END AS target_name,
    l.reason,
    l.ip_address,
    l.user_agent,
    l.created_at
FROM admin_audit_logs l
LEFT JOIN admin_users au ON au.id = l.admin_user_id
LEFT JOIN admin_users target_admin ON l.target_type = 'ADMIN_USER' AND target_admin.id = l.target_id
LEFT JOIN organizers target_organizer ON l.target_type = 'ORGANIZER' AND target_organizer.id = l.target_id
LEFT JOIN events target_event ON l.target_type = 'EVENT' AND target_event.id = l.target_id
LEFT JOIN event_sections target_section ON l.target_type = 'SECTION' AND target_section.id = l.target_id
LEFT JOIN orders target_order ON l.target_type = 'ORDER' AND target_order.id = l.target_id
WHERE ($1::bigint = 0 OR l.admin_user_id = $1)
  AND (
      $2::timestamptz IS NULL
      OR l.created_at < $2
      OR (l.created_at = $2 AND l.id < $3)
  )
ORDER BY l.created_at DESC, l.id DESC
LIMIT $4
`

type ListAdminAuditLogsParams struct {
	AdminUserID     int64              `json:"admin_user_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListAdminAuditLogsRow struct {
	ID              int64              `json:"id"`
	AdminUserID     int64              `json:"admin_user_id"`
	AdminUserName   pgtype.Text        `json:"admin_user_name"`
	AdminUserEmail  pgtype.Text        `json:"admin_user_email"`
	AdminUserRole   pgtype.Text        `json:"admin_user_role"`
	AdminUserStatus pgtype.Int2        `json:"admin_user_status"`
	Action          string             `json:"action"`
	TargetType      string             `json:"target_type"`
	TargetID        int64              `json:"target_id"`
	TargetName      interface{}        `json:"target_name"`
	Reason          pgtype.Text        `json:"reason"`
	IpAddress       pgtype.Text        `json:"ip_address"`
	UserAgent       pgtype.Text        `json:"user_agent"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAdminAuditLogs(ctx context.Context, arg ListAdminAuditLogsParams) ([]ListAdminAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAdminAuditLogs,
		arg.AdminUserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminAuditLogsRow{}
	for rows.Next() {
		var i ListAdminAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminUserID,
			&i.AdminUserName,
			&i.AdminUserEmail,
			&i.AdminUserRole,
			&i.AdminUserStatus,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.TargetName,
			&i.Reason,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
