// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceEventStatuses = `-- name: AdvanceEventStatuses :execrows
UPDATE events
SET
    status = CASE
        WHEN status = 2 AND sale_end_at < $1::timestamptz THEN 4
        WHEN status = 2
             AND sale_start_at <= $1::timestamptz
             AND sale_end_at >= $1::timestamptz THEN 3
        WHEN status = 3 AND sale_end_at < $1::timestamptz THEN 4
        ELSE status
    END,
    updated_at = $1::timestamptz
WHERE
    (status = 2 AND sale_end_at < $1::timestamptz)
    OR (
        status = 2
        AND sale_start_at <= $1::timestamptz
        AND sale_end_at >= $1::timestamptz
    )
    OR (status = 3 AND sale_end_at < $1::timestamptz)
`

func (q *Queries) AdvanceEventStatuses(ctx context.Context, now pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, advanceEventStatuses, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    organizer_id,
    name,
    venue,
    status,
    start_at,
    end_at,
    sale_start_at,
    sale_end_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING
    id,
    organizer_id,
    name,
    venue,
    status,
    start_at,
    end_at,
    sale_start_at,
    sale_end_at,
    created_at,
    updated_at
`

type CreateEventParams struct {
	OrganizerID int64              `json:"organizer_id"`
	Name        string             `json:"name"`
	Venue       string             `json:"venue"`
	Status      int16              `json:"status"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	SaleStartAt pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt   pgtype.Timestamptz `json:"sale_end_at"`
}

type CreateEventRow struct {
	ID          int64              `json:"id"`
	OrganizerID int64              `json:"organizer_id"`
	Name        string             `json:"name"`
	Venue       string             `json:"venue"`
	Status      int16              `json:"status"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	SaleStartAt pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt   pgtype.Timestamptz `json:"sale_end_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.OrganizerID,
		arg.Name,
		arg.Venue,
		arg.Status,
		arg.StartAt,
		arg.EndAt,
		arg.SaleStartAt,
		arg.SaleEndAt,
	)
	var i CreateEventRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Venue,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.SaleStartAt,
		&i.SaleEndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminEventByID = `-- name: GetAdminEventByID :one
SELECT
    e.id,
    e.organizer_id,
    o.name AS organizer_name,
    o.status AS organizer_status,
    e.name,
    e.venue,
    e.status,
    e.start_at,
    e.end_at,
    e.sale_start_at,
    e.sale_end_at,
    e.created_at,
    e.updated_at
FROM events e
LEFT JOIN organizers o ON o.id = e.organizer_id
WHERE e.id = $1
  AND (
      $2::bigint = 0
      OR e.organizer_id = $2
  )
LIMIT 1
`

type GetAdminEventByIDParams struct {
	EventID     int64 `json:"event_id"`
	OrganizerID int64 `json:"organizer_id"`
}

type GetAdminEventByIDRow struct {
	ID              int64              `json:"id"`
	OrganizerID     int64              `json:"organizer_id"`
	OrganizerName   pgtype.Text        `json:"organizer_name"`
	OrganizerStatus pgtype.Int2        `json:"organizer_status"`
	Name            string             `json:"name"`
	Venue           string             `json:"venue"`
	Status          int16              `json:"status"`
	StartAt         pgtype.Timestamptz `json:"start_at"`
	EndAt           pgtype.Timestamptz `json:"end_at"`
	SaleStartAt     pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt       pgtype.Timestamptz `json:"sale_end_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAdminEventByID(ctx context.Context, arg GetAdminEventByIDParams) (GetAdminEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminEventByID, arg.EventID, arg.OrganizerID)
	var i GetAdminEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.OrganizerName,
		&i.OrganizerStatus,
		&i.Name,
		&i.Venue,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.SaleStartAt,
		&i.SaleEndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT
    id,
    organizer_id,
    name,
    venue,
    status,
    start_at,
    end_at,
    sale_start_at,
    sale_end_at,
    created_at,
    updated_at
FROM events
WHERE id = $1
LIMIT 1
`

type GetEventByIDRow struct {
	ID          int64              `json:"id"`
	OrganizerID int64              `json:"organizer_id"`
	Name        string             `json:"name"`
	Venue       string             `json:"venue"`
	Status      int16              `json:"status"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	SaleStartAt pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt   pgtype.Timestamptz `json:"sale_end_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEventByID(ctx context.Context, id int64) (GetEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Venue,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.SaleStartAt,
		&i.SaleEndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminEvents = `-- name: ListAdminEvents :many
SELECT
    e.id,
    e.organizer_id,
    o.name AS organizer_name,
    o.status AS organizer_status,
    e.name,
    e.venue,
    e.status,
    e.start_at,
    e.end_at,
    e.sale_start_at,
    e.sale_end_at,
    e.created_at,
    e.updated_at
FROM events e
LEFT JOIN organizers o ON o.id = e.organizer_id
WHERE $1::bigint = 0
   OR e.organizer_id = $1
ORDER BY e.id
`

type ListAdminEventsRow struct {
	ID              int64              `json:"id"`
	OrganizerID     int64              `json:"organizer_id"`
	OrganizerName   pgtype.Text        `json:"organizer_name"`
	OrganizerStatus pgtype.Int2        `json:"organizer_status"`
	Name            string             `json:"name"`
	Venue           string             `json:"venue"`
	Status          int16              `json:"status"`
	StartAt         pgtype.Timestamptz `json:"start_at"`
	EndAt           pgtype.Timestamptz `json:"end_at"`
	SaleStartAt     pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt       pgtype.Timestamptz `json:"sale_end_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAdminEvents(ctx context.Context, organizerID int64) ([]ListAdminEventsRow, error) {
	rows, err := q.db.Query(ctx, listAdminEvents, organizerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminEventsRow{}
	for rows.Next() {
		var i ListAdminEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.OrganizerName,
			&i.OrganizerStatus,
			&i.Name,
			&i.Venue,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.SaleStartAt,
			&i.SaleEndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT
    id,
    organizer_id,
    name,
    venue,
    status,
    start_at,
    end_at,
    sale_start_at,
    sale_end_at,
    created_at,
    updated_at
FROM events
ORDER BY id
`

type ListEventsRow struct {
	ID          int64              `json:"id"`
	OrganizerID int64              `json:"organizer_id"`
	Name        string             `json:"name"`
	Venue       string             `json:"venue"`
	Status      int16              `json:"status"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	SaleStartAt pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt   pgtype.Timestamptz `json:"sale_end_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListEvents(ctx context.Context) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Name,
			&i.Venue,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.SaleStartAt,
			&i.SaleEndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET
    organizer_id = $2,
    name = $3,
    venue = $4,
    status = $5,
    start_at = $6,
    end_at = $7,
    sale_start_at = $8,
    sale_end_at = $9,
    updated_at = $10
WHERE id = $1
RETURNING
    id,
    organizer_id,
    name,
    venue,
    status,
    start_at,
    end_at,
    sale_start_at,
    sale_end_at,
    created_at,
    updated_at
`

type UpdateEventParams struct {
	ID          int64              `json:"id"`
	OrganizerID int64              `json:"organizer_id"`
	Name        string             `json:"name"`
	Venue       string             `json:"venue"`
	Status      int16              `json:"status"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	SaleStartAt pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt   pgtype.Timestamptz `json:"sale_end_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UpdateEventRow struct {
	ID          int64              `json:"id"`
	OrganizerID int64              `json:"organizer_id"`
	Name        string             `json:"name"`
	Venue       string             `json:"venue"`
	Status      int16              `json:"status"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	SaleStartAt pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt   pgtype.Timestamptz `json:"sale_end_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (UpdateEventRow, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.OrganizerID,
		arg.Name,
		arg.Venue,
		arg.Status,
		arg.StartAt,
		arg.EndAt,
		arg.SaleStartAt,
		arg.SaleEndAt,
		arg.UpdatedAt,
	)
	var i UpdateEventRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Venue,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.SaleStartAt,
		&i.SaleEndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
