// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET
    status = $1,
    response_status = $2,
    response_body = $3,
    locked_until = NULL,
    updated_at = $4
WHERE user_id = $5
  AND key = $6
  AND endpoint = $7
`

type CompleteIdempotencyKeyParams struct {
	Status         int16              `json:"status"`
	ResponseStatus pgtype.Int4        `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UserID         int64              `json:"user_id"`
	Key            string             `json:"key"`
	Endpoint       string             `json:"endpoint"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.Status,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.UpdatedAt,
		arg.UserID,
		arg.Key,
		arg.Endpoint,
	)
	return err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (
    key,
    user_id,
    endpoint,
    request_hash,
    status,
    locked_until,
    expires_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $8
)
RETURNING
    id,
    key,
    user_id,
    endpoint,
    request_hash,
    status,
    response_status,
    response_body,
    locked_until,
    expires_at,
    created_at,
    updated_at
`

type CreateIdempotencyKeyParams struct {
	Key         string             `json:"key"`
	UserID      int64              `json:"user_id"`
	Endpoint    string             `json:"endpoint"`
	RequestHash string             `json:"request_hash"`
	Status      int16              `json:"status"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.Key,
		arg.UserID,
		arg.Endpoint,
		arg.RequestHash,
		arg.Status,
		arg.LockedUntil,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserID,
		&i.Endpoint,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LockedUntil,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT
    id,
    key,
    user_id,
    endpoint,
    request_hash,
    status,
    response_status,
    response_body,
    locked_until,
    expires_at,
    created_at,
    updated_at
FROM idempotency_keys
WHERE user_id = $1
  AND key = $2
  AND endpoint = $3
LIMIT 1
`

type GetIdempotencyKeyParams struct {
	UserID   int64  `json:"user_id"`
	Key      string `json:"key"`
	Endpoint string `json:"endpoint"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.Key, arg.Endpoint)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserID,
		&i.Endpoint,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LockedUntil,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
