// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAuditLog struct {
	ID          int64              `json:"id"`
	AdminUserID int64              `json:"admin_user_id"`
	Action      string             `json:"action"`
	TargetType  string             `json:"target_type"`
	TargetID    int64              `json:"target_id"`
	Reason      pgtype.Text        `json:"reason"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AdminUser struct {
	ID           int64              `json:"id"`
	OrganizerID  pgtype.Int8        `json:"organizer_id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Status       int16              `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Version      int64              `json:"version"`
}

type Event struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Venue       string             `json:"venue"`
	Status      int16              `json:"status"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	SaleStartAt pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt   pgtype.Timestamptz `json:"sale_end_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	OrganizerID int64              `json:"organizer_id"`
	Version     int64              `json:"version"`
}

type EventSection struct {
	ID               int64              `json:"id"`
	EventID          int64              `json:"event_id"`
	EventName        string             `json:"event_name"`
	SectionName      string             `json:"section_name"`
	Price            int64              `json:"price"`
	TotalQuantity    int32              `json:"total_quantity"`
	ReservedQuantity int32              `json:"reserved_quantity"`
	SoldQuantity     int32              `json:"sold_quantity"`
	PurchaseLimit    int32              `json:"purchase_limit"`
	Status           int16              `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Version          int64              `json:"version"`
}

type IdempotencyKey struct {
	ID             int64              `json:"id"`
	Key            string             `json:"key"`
	UserID         pgtype.Int8        `json:"user_id"`
	Endpoint       string             `json:"endpoint"`
	RequestHash    string             `json:"request_hash"`
	Status         int16              `json:"status"`
	ResponseStatus pgtype.Int4        `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID            int64              `json:"id"`
	OrderNo       string             `json:"order_no"`
	ReservationID int64              `json:"reservation_id"`
	ReservationNo string             `json:"reservation_no"`
	EventID       int64              `json:"event_id"`
	EventName     string             `json:"event_name"`
	SectionID     int64              `json:"section_id"`
	SectionName   string             `json:"section_name"`
	UserID        int64              `json:"user_id"`
	UserName      string             `json:"user_name"`
	Quantity      int32              `json:"quantity"`
	UnitPrice     int64              `json:"unit_price"`
	TotalAmount   int64              `json:"total_amount"`
	Status        int16              `json:"status"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Organizer struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Status    int16              `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Version   int64              `json:"version"`
}

type OutboxEvent struct {
	ID            int64              `json:"id"`
	EventID       string             `json:"event_id"`
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   int64              `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	Status        int16              `json:"status"`
	Attempts      int32              `json:"attempts"`
	MaxAttempts   int32              `json:"max_attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     pgtype.Text        `json:"last_error"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID            int64              `json:"id"`
	PaymentNo     string             `json:"payment_no"`
	OrderID       int64              `json:"order_id"`
	OrderNo       string             `json:"order_no"`
	ReservationID int64              `json:"reservation_id"`
	EventID       int64              `json:"event_id"`
	EventName     string             `json:"event_name"`
	UserID        int64              `json:"user_id"`
	UserName      string             `json:"user_name"`
	Method        string             `json:"method"`
	Amount        int64              `json:"amount"`
	Status        int16              `json:"status"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	FailedAt      pgtype.Timestamptz `json:"failed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type PaymentAttempt struct {
	ID                 int64              `json:"id"`
	OrderID            int64              `json:"order_id"`
	PaymentID          pgtype.Int8        `json:"payment_id"`
	IdempotencyKey     pgtype.Text        `json:"idempotency_key"`
	Provider           string             `json:"provider"`
	MerchantTradeNo    string             `json:"merchant_trade_no"`
	ProviderTradeNo    pgtype.Text        `json:"provider_trade_no"`
	Method             string             `json:"method"`
	Amount             int64              `json:"amount"`
	Status             int16              `json:"status"`
	RequestPayload     []byte             `json:"request_payload"`
	ResponsePayload    []byte             `json:"response_payload"`
	CallbackPayload    []byte             `json:"callback_payload"`
	FailureReason      pgtype.Text        `json:"failure_reason"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	SucceededAt        pgtype.Timestamptz `json:"succeeded_at"`
	FailedAt           pgtype.Timestamptz `json:"failed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ReconcileAttempts  int32              `json:"reconcile_attempts"`
	NextReconcileAt    pgtype.Timestamptz `json:"next_reconcile_at"`
	LastReconcileError pgtype.Text        `json:"last_reconcile_error"`
}

type Reservation struct {
	ID            int64              `json:"id"`
	ReservationNo string             `json:"reservation_no"`
	EventID       int64              `json:"event_id"`
	EventName     string             `json:"event_name"`
	SectionID     int64              `json:"section_id"`
	SectionName   string             `json:"section_name"`
	UserID        int64              `json:"user_id"`
	UserName      string             `json:"user_name"`
	Quantity      int32              `json:"quantity"`
	UnitPrice     int64              `json:"unit_price"`
	TotalAmount   int64              `json:"total_amount"`
	Status        int16              `json:"status"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	PasswordHash string             `json:"password_hash"`
}
