// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Venue       string             `json:"venue"`
	Status      int16              `json:"status"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	SaleStartAt pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt   pgtype.Timestamptz `json:"sale_end_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type EventSection struct {
	ID               int64              `json:"id"`
	EventID          int64              `json:"event_id"`
	EventName        string             `json:"event_name"`
	SectionName      string             `json:"section_name"`
	Price            int64              `json:"price"`
	TotalQuantity    int32              `json:"total_quantity"`
	ReservedQuantity int32              `json:"reserved_quantity"`
	SoldQuantity     int32              `json:"sold_quantity"`
	PurchaseLimit    int32              `json:"purchase_limit"`
	Status           int16              `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type IdempotencyKey struct {
	ID             int64              `json:"id"`
	Key            string             `json:"key"`
	UserID         pgtype.Int8        `json:"user_id"`
	Endpoint       string             `json:"endpoint"`
	RequestHash    string             `json:"request_hash"`
	Status         int16              `json:"status"`
	ResponseStatus pgtype.Int4        `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID            int64              `json:"id"`
	OrderNo       string             `json:"order_no"`
	ReservationID int64              `json:"reservation_id"`
	ReservationNo string             `json:"reservation_no"`
	EventID       int64              `json:"event_id"`
	EventName     string             `json:"event_name"`
	SectionID     int64              `json:"section_id"`
	SectionName   string             `json:"section_name"`
	UserID        int64              `json:"user_id"`
	UserName      string             `json:"user_name"`
	Quantity      int32              `json:"quantity"`
	UnitPrice     int64              `json:"unit_price"`
	TotalAmount   int64              `json:"total_amount"`
	Status        int16              `json:"status"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID            int64              `json:"id"`
	PaymentNo     string             `json:"payment_no"`
	OrderID       int64              `json:"order_id"`
	OrderNo       string             `json:"order_no"`
	ReservationID int64              `json:"reservation_id"`
	EventID       int64              `json:"event_id"`
	EventName     string             `json:"event_name"`
	UserID        int64              `json:"user_id"`
	UserName      string             `json:"user_name"`
	Method        string             `json:"method"`
	Amount        int64              `json:"amount"`
	Status        int16              `json:"status"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	FailedAt      pgtype.Timestamptz `json:"failed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Reservation struct {
	ID            int64              `json:"id"`
	ReservationNo string             `json:"reservation_no"`
	EventID       int64              `json:"event_id"`
	EventName     string             `json:"event_name"`
	SectionID     int64              `json:"section_id"`
	SectionName   string             `json:"section_name"`
	UserID        int64              `json:"user_id"`
	UserName      string             `json:"user_name"`
	Quantity      int32              `json:"quantity"`
	UnitPrice     int64              `json:"unit_price"`
	TotalAmount   int64              `json:"total_amount"`
	Status        int16              `json:"status"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	PasswordHash string             `json:"password_hash"`
}
