// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING
    id,
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
`

type CreateOrderParams struct {
	OrderNo       string             `json:"order_no"`
	ReservationID int64              `json:"reservation_id"`
	ReservationNo string             `json:"reservation_no"`
	EventID       int64              `json:"event_id"`
	EventName     string             `json:"event_name"`
	SectionID     int64              `json:"section_id"`
	SectionName   string             `json:"section_name"`
	UserID        int64              `json:"user_id"`
	UserName      string             `json:"user_name"`
	Quantity      int32              `json:"quantity"`
	UnitPrice     int64              `json:"unit_price"`
	TotalAmount   int64              `json:"total_amount"`
	Status        int16              `json:"status"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderNo,
		arg.ReservationID,
		arg.ReservationNo,
		arg.EventID,
		arg.EventName,
		arg.SectionID,
		arg.SectionName,
		arg.UserID,
		arg.UserName,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalAmount,
		arg.Status,
		arg.ExpiresAt,
		arg.PaidAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.ReservationID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminOrderSensitiveByID = `-- name: GetAdminOrderSensitiveByID :one
SELECT
    o.id,
    o.order_no,
    o.reservation_id,
    o.reservation_no,
    o.event_id,
    o.event_name,
    o.section_id,
    o.section_name,
    o.user_id,
    o.user_name,
    u.email AS user_email,
    o.quantity,
    o.unit_price,
    o.total_amount,
    o.status,
    o.expires_at,
    o.paid_at,
    o.created_at,
    o.updated_at
FROM orders o
JOIN users u ON u.id = o.user_id
WHERE o.id = $1
LIMIT 1
`

type GetAdminOrderSensitiveByIDRow struct {
	ID            int64              `json:"id"`
	OrderNo       string             `json:"order_no"`
	ReservationID int64              `json:"reservation_id"`
	ReservationNo string             `json:"reservation_no"`
	EventID       int64              `json:"event_id"`
	EventName     string             `json:"event_name"`
	SectionID     int64              `json:"section_id"`
	SectionName   string             `json:"section_name"`
	UserID        int64              `json:"user_id"`
	UserName      string             `json:"user_name"`
	UserEmail     string             `json:"user_email"`
	Quantity      int32              `json:"quantity"`
	UnitPrice     int64              `json:"unit_price"`
	TotalAmount   int64              `json:"total_amount"`
	Status        int16              `json:"status"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAdminOrderSensitiveByID(ctx context.Context, id int64) (GetAdminOrderSensitiveByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminOrderSensitiveByID, id)
	var i GetAdminOrderSensitiveByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.ReservationID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.UserEmail,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
    id,
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
FROM orders
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.ReservationID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByIDForUpdate = `-- name: GetOrderByIDForUpdate :one
SELECT
    id,
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
FROM orders
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetOrderByIDForUpdate(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIDForUpdate, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.ReservationID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByOrderNo = `-- name: GetOrderByOrderNo :one
SELECT
    id,
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
FROM orders
WHERE order_no = $1
LIMIT 1
`

func (q *Queries) GetOrderByOrderNo(ctx context.Context, orderNo string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByOrderNo, orderNo)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.ReservationID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminOrders = `-- name: ListAdminOrders :many
SELECT
    o.id,
    o.order_no,
    o.reservation_id,
    o.reservation_no,
    o.event_id,
    o.event_name,
    o.section_id,
    o.section_name,
    o.user_id,
    o.user_name,
    u.email AS user_email,
    o.quantity,
    o.unit_price,
    o.total_amount,
    o.status,
    o.expires_at,
    o.paid_at,
    o.created_at,
    o.updated_at
FROM orders o
JOIN events e ON e.id = o.event_id
JOIN users u ON u.id = o.user_id
WHERE ($1::bigint = 0 OR e.organizer_id = $1)
  AND ($2::bigint = 0 OR o.event_id = $2)
  AND ($3::bigint = 0 OR o.user_id = $3)
  AND ($4::smallint = 0 OR o.status = $4)
  AND (
      $5::timestamptz IS NULL
      OR o.created_at < $5
      OR (o.created_at = $5 AND o.id < $6)
  )
ORDER BY o.created_at DESC, o.id DESC
LIMIT $7
`

type ListAdminOrdersParams struct {
	OrganizerID     int64              `json:"organizer_id"`
	EventID         int64              `json:"event_id"`
	UserID          int64              `json:"user_id"`
	Status          int16              `json:"status"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        int64              `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListAdminOrdersRow struct {
	ID            int64              `json:"id"`
	OrderNo       string             `json:"order_no"`
	ReservationID int64              `json:"reservation_id"`
	ReservationNo string             `json:"reservation_no"`
	EventID       int64              `json:"event_id"`
	EventName     string             `json:"event_name"`
	SectionID     int64              `json:"section_id"`
	SectionName   string             `json:"section_name"`
	UserID        int64              `json:"user_id"`
	UserName      string             `json:"user_name"`
	UserEmail     string             `json:"user_email"`
	Quantity      int32              `json:"quantity"`
	UnitPrice     int64              `json:"unit_price"`
	TotalAmount   int64              `json:"total_amount"`
	Status        int16              `json:"status"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAdminOrders(ctx context.Context, arg ListAdminOrdersParams) ([]ListAdminOrdersRow, error) {
	rows, err := q.db.Query(ctx, listAdminOrders,
		arg.OrganizerID,
		arg.EventID,
		arg.UserID,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminOrdersRow{}
	for rows.Next() {
		var i ListAdminOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.ReservationID,
			&i.ReservationNo,
			&i.EventID,
			&i.EventName,
			&i.SectionID,
			&i.SectionName,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Status,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPendingOrders = `-- name: ListExpiredPendingOrders :many
SELECT
    id,
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
FROM orders
WHERE status = 1
  AND expires_at <= $1
ORDER BY expires_at
LIMIT $2
`

type ListExpiredPendingOrdersParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListExpiredPendingOrders(ctx context.Context, arg ListExpiredPendingOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingOrders, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.ReservationID,
			&i.ReservationNo,
			&i.EventID,
			&i.EventName,
			&i.SectionID,
			&i.SectionName,
			&i.UserID,
			&i.UserName,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Status,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT
    id,
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListOrdersByUserID(ctx context.Context, userID int64) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.ReservationID,
			&i.ReservationNo,
			&i.EventID,
			&i.EventName,
			&i.SectionID,
			&i.SectionName,
			&i.UserID,
			&i.UserName,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Status,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET
    status = $2,
    paid_at = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID        int64              `json:"id"`
	Status    int16              `json:"status"`
	PaidAt    pgtype.Timestamptz `json:"paid_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus,
		arg.ID,
		arg.Status,
		arg.PaidAt,
		arg.UpdatedAt,
	)
	return err
}

const updateOrderStatusIfCurrent = `-- name: UpdateOrderStatusIfCurrent :execrows
UPDATE orders
SET
    status = $1,
    paid_at = $2,
    updated_at = $3
WHERE id = $4
  AND status = $5
`

type UpdateOrderStatusIfCurrentParams struct {
	Status         int16              `json:"status"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ID             int64              `json:"id"`
	ExpectedStatus int16              `json:"expected_status"`
}

func (q *Queries) UpdateOrderStatusIfCurrent(ctx context.Context, arg UpdateOrderStatusIfCurrentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderStatusIfCurrent,
		arg.Status,
		arg.PaidAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
