// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizer.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganizer = `-- name: CreateOrganizer :one
INSERT INTO organizers (
    name,
    status
) VALUES (
    $1, $2
)
RETURNING
    id,
    name,
    status,
    version,
    created_at,
    updated_at
`

type CreateOrganizerParams struct {
	Name   string `json:"name"`
	Status int16  `json:"status"`
}

type CreateOrganizerRow struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Status    int16              `json:"status"`
	Version   int64              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOrganizer(ctx context.Context, arg CreateOrganizerParams) (CreateOrganizerRow, error) {
	row := q.db.QueryRow(ctx, createOrganizer, arg.Name, arg.Status)
	var i CreateOrganizerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizerByID = `-- name: GetOrganizerByID :one
SELECT
    id,
    name,
    status,
    version,
    created_at,
    updated_at
FROM organizers
WHERE id = $1
LIMIT 1
`

type GetOrganizerByIDRow struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Status    int16              `json:"status"`
	Version   int64              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOrganizerByID(ctx context.Context, id int64) (GetOrganizerByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizerByID, id)
	var i GetOrganizerByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizers = `-- name: ListOrganizers :many
SELECT
    id,
    name,
    status,
    version,
    created_at,
    updated_at
FROM organizers
ORDER BY id
`

type ListOrganizersRow struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Status    int16              `json:"status"`
	Version   int64              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListOrganizers(ctx context.Context) ([]ListOrganizersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizersRow{}
	for rows.Next() {
		var i ListOrganizersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganizer = `-- name: UpdateOrganizer :one
UPDATE organizers
SET
    name = $2,
    status = $3,
    version = version + 1,
    updated_at = $4
WHERE id = $1
  AND version = $5
RETURNING
    id,
    name,
    status,
    version,
    created_at,
    updated_at
`

type UpdateOrganizerParams struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Status    int16              `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Version   int64              `json:"version"`
}

type UpdateOrganizerRow struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Status    int16              `json:"status"`
	Version   int64              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOrganizer(ctx context.Context, arg UpdateOrganizerParams) (UpdateOrganizerRow, error) {
	row := q.db.QueryRow(ctx, updateOrganizer,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.UpdatedAt,
		arg.Version,
	)
	var i UpdateOrganizerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
