// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox_event.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (
    event_id,
    event_type,
    aggregate_type,
    aggregate_id,
    payload,
    status,
    attempts,
    max_attempts,
    next_attempt_at,
    last_error,
    published_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $12
)
RETURNING
    id,
    event_id,
    event_type,
    aggregate_type,
    aggregate_id,
    payload,
    status,
    attempts,
    max_attempts,
    next_attempt_at,
    last_error,
    published_at,
    created_at,
    updated_at
`

type CreateOutboxEventParams struct {
	EventID       string             `json:"event_id"`
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   int64              `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	Status        int16              `json:"status"`
	Attempts      int32              `json:"attempts"`
	MaxAttempts   int32              `json:"max_attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     pgtype.Text        `json:"last_error"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.EventID,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
		arg.Status,
		arg.Attempts,
		arg.MaxAttempts,
		arg.NextAttemptAt,
		arg.LastError,
		arg.PublishedAt,
		arg.CreatedAt,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingOutboxEvents = `-- name: ListPendingOutboxEvents :many
SELECT
    id,
    event_id,
    event_type,
    aggregate_type,
    aggregate_id,
    payload,
    status,
    attempts,
    max_attempts,
    next_attempt_at,
    last_error,
    published_at,
    created_at,
    updated_at
FROM outbox_events
WHERE status = 1
  AND attempts < max_attempts
  AND (
      next_attempt_at IS NULL
      OR next_attempt_at <= $1::timestamptz
  )
ORDER BY created_at ASC, id ASC
LIMIT $2::integer
`

type ListPendingOutboxEventsParams struct {
	Now       pgtype.Timestamptz `json:"now"`
	LimitRows int32              `json:"limit_rows"`
}

func (q *Queries) ListPendingOutboxEvents(ctx context.Context, arg ListPendingOutboxEventsParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listPendingOutboxEvents, arg.Now, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOutboxEventPublishState = `-- name: UpdateOutboxEventPublishState :exec
UPDATE outbox_events
SET
    status = $2,
    attempts = $3,
    next_attempt_at = $4,
    last_error = $5,
    published_at = $6,
    updated_at = $7
WHERE id = $1
`

type UpdateOutboxEventPublishStateParams struct {
	ID            int64              `json:"id"`
	Status        int16              `json:"status"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     pgtype.Text        `json:"last_error"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOutboxEventPublishState(ctx context.Context, arg UpdateOutboxEventPublishStateParams) error {
	_, err := q.db.Exec(ctx, updateOutboxEventPublishState,
		arg.ID,
		arg.Status,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.LastError,
		arg.PublishedAt,
		arg.UpdatedAt,
	)
	return err
}
