// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    payment_no,
    order_id,
    order_no,
    reservation_id,
    event_id,
    event_name,
    user_id,
    user_name,
    method,
    amount,
    status,
    paid_at,
    failed_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING
    id,
    payment_no,
    order_id,
    order_no,
    reservation_id,
    event_id,
    event_name,
    user_id,
    user_name,
    method,
    amount,
    status,
    paid_at,
    failed_at,
    created_at,
    updated_at
`

type CreatePaymentParams struct {
	PaymentNo     string             `json:"payment_no"`
	OrderID       int64              `json:"order_id"`
	OrderNo       string             `json:"order_no"`
	ReservationID int64              `json:"reservation_id"`
	EventID       int64              `json:"event_id"`
	EventName     string             `json:"event_name"`
	UserID        int64              `json:"user_id"`
	UserName      string             `json:"user_name"`
	Method        string             `json:"method"`
	Amount        int64              `json:"amount"`
	Status        int16              `json:"status"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	FailedAt      pgtype.Timestamptz `json:"failed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.PaymentNo,
		arg.OrderID,
		arg.OrderNo,
		arg.ReservationID,
		arg.EventID,
		arg.EventName,
		arg.UserID,
		arg.UserName,
		arg.Method,
		arg.Amount,
		arg.Status,
		arg.PaidAt,
		arg.FailedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.OrderNo,
		&i.ReservationID,
		&i.EventID,
		&i.EventName,
		&i.UserID,
		&i.UserName,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.PaidAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByPaymentNo = `-- name: GetPaymentByPaymentNo :one
SELECT
    id,
    payment_no,
    order_id,
    order_no,
    reservation_id,
    event_id,
    event_name,
    user_id,
    user_name,
    method,
    amount,
    status,
    paid_at,
    failed_at,
    created_at,
    updated_at
FROM payments
WHERE payment_no = $1
LIMIT 1
`

func (q *Queries) GetPaymentByPaymentNo(ctx context.Context, paymentNo string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByPaymentNo, paymentNo)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.OrderNo,
		&i.ReservationID,
		&i.EventID,
		&i.EventName,
		&i.UserID,
		&i.UserName,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.PaidAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentsByUserID = `-- name: ListPaymentsByUserID :many
SELECT
    id,
    payment_no,
    order_id,
    order_no,
    reservation_id,
    event_id,
    event_name,
    user_id,
    user_name,
    method,
    amount,
    status,
    paid_at,
    failed_at,
    created_at,
    updated_at
FROM payments
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPaymentsByUserID(ctx context.Context, userID int64) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.PaymentNo,
			&i.OrderID,
			&i.OrderNo,
			&i.ReservationID,
			&i.EventID,
			&i.EventName,
			&i.UserID,
			&i.UserName,
			&i.Method,
			&i.Amount,
			&i.Status,
			&i.PaidAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments
SET
    status = $2,
    paid_at = $3,
    failed_at = $4,
    updated_at = $5
WHERE id = $1
`

type UpdatePaymentStatusParams struct {
	ID        int64              `json:"id"`
	Status    int16              `json:"status"`
	PaidAt    pgtype.Timestamptz `json:"paid_at"`
	FailedAt  pgtype.Timestamptz `json:"failed_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus,
		arg.ID,
		arg.Status,
		arg.PaidAt,
		arg.FailedAt,
		arg.UpdatedAt,
	)
	return err
}
