// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_attempt.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentAttempt = `-- name: CreatePaymentAttempt :one
INSERT INTO payment_attempts (
    order_id,
    payment_id,
    idempotency_key,
    provider,
    merchant_trade_no,
    provider_trade_no,
    method,
    amount,
    status,
    request_payload,
    response_payload,
    callback_payload,
    failure_reason,
    expires_at,
    succeeded_at,
    failed_at,
    reconcile_attempts,
    next_reconcile_at,
    last_reconcile_error,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $20
)
RETURNING
    id,
    order_id,
    payment_id,
    idempotency_key,
    provider,
    merchant_trade_no,
    provider_trade_no,
    method,
    amount,
    status,
    request_payload,
    response_payload,
    callback_payload,
    failure_reason,
    expires_at,
    succeeded_at,
    failed_at,
    reconcile_attempts,
    next_reconcile_at,
    last_reconcile_error,
    created_at,
    updated_at
`

type CreatePaymentAttemptParams struct {
	OrderID            int64              `json:"order_id"`
	PaymentID          pgtype.Int8        `json:"payment_id"`
	IdempotencyKey     pgtype.Text        `json:"idempotency_key"`
	Provider           string             `json:"provider"`
	MerchantTradeNo    string             `json:"merchant_trade_no"`
	ProviderTradeNo    pgtype.Text        `json:"provider_trade_no"`
	Method             string             `json:"method"`
	Amount             int64              `json:"amount"`
	Status             int16              `json:"status"`
	RequestPayload     []byte             `json:"request_payload"`
	ResponsePayload    []byte             `json:"response_payload"`
	CallbackPayload    []byte             `json:"callback_payload"`
	FailureReason      pgtype.Text        `json:"failure_reason"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	SucceededAt        pgtype.Timestamptz `json:"succeeded_at"`
	FailedAt           pgtype.Timestamptz `json:"failed_at"`
	ReconcileAttempts  int32              `json:"reconcile_attempts"`
	NextReconcileAt    pgtype.Timestamptz `json:"next_reconcile_at"`
	LastReconcileError pgtype.Text        `json:"last_reconcile_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type CreatePaymentAttemptRow struct {
	ID                 int64              `json:"id"`
	OrderID            int64              `json:"order_id"`
	PaymentID          pgtype.Int8        `json:"payment_id"`
	IdempotencyKey     pgtype.Text        `json:"idempotency_key"`
	Provider           string             `json:"provider"`
	MerchantTradeNo    string             `json:"merchant_trade_no"`
	ProviderTradeNo    pgtype.Text        `json:"provider_trade_no"`
	Method             string             `json:"method"`
	Amount             int64              `json:"amount"`
	Status             int16              `json:"status"`
	RequestPayload     []byte             `json:"request_payload"`
	ResponsePayload    []byte             `json:"response_payload"`
	CallbackPayload    []byte             `json:"callback_payload"`
	FailureReason      pgtype.Text        `json:"failure_reason"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	SucceededAt        pgtype.Timestamptz `json:"succeeded_at"`
	FailedAt           pgtype.Timestamptz `json:"failed_at"`
	ReconcileAttempts  int32              `json:"reconcile_attempts"`
	NextReconcileAt    pgtype.Timestamptz `json:"next_reconcile_at"`
	LastReconcileError pgtype.Text        `json:"last_reconcile_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePaymentAttempt(ctx context.Context, arg CreatePaymentAttemptParams) (CreatePaymentAttemptRow, error) {
	row := q.db.QueryRow(ctx, createPaymentAttempt,
		arg.OrderID,
		arg.PaymentID,
		arg.IdempotencyKey,
		arg.Provider,
		arg.MerchantTradeNo,
		arg.ProviderTradeNo,
		arg.Method,
		arg.Amount,
		arg.Status,
		arg.RequestPayload,
		arg.ResponsePayload,
		arg.CallbackPayload,
		arg.FailureReason,
		arg.ExpiresAt,
		arg.SucceededAt,
		arg.FailedAt,
		arg.ReconcileAttempts,
		arg.NextReconcileAt,
		arg.LastReconcileError,
		arg.CreatedAt,
	)
	var i CreatePaymentAttemptRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.Provider,
		&i.MerchantTradeNo,
		&i.ProviderTradeNo,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.CallbackPayload,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.SucceededAt,
		&i.FailedAt,
		&i.ReconcileAttempts,
		&i.NextReconcileAt,
		&i.LastReconcileError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentAttemptByIdempotencyKey = `-- name: GetPaymentAttemptByIdempotencyKey :one
SELECT
    id,
    order_id,
    payment_id,
    idempotency_key,
    provider,
    merchant_trade_no,
    provider_trade_no,
    method,
    amount,
    status,
    request_payload,
    response_payload,
    callback_payload,
    failure_reason,
    expires_at,
    succeeded_at,
    failed_at,
    reconcile_attempts,
    next_reconcile_at,
    last_reconcile_error,
    created_at,
    updated_at
FROM payment_attempts
WHERE order_id = $1
  AND idempotency_key = $2
LIMIT 1
`

type GetPaymentAttemptByIdempotencyKeyParams struct {
	OrderID        int64       `json:"order_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

type GetPaymentAttemptByIdempotencyKeyRow struct {
	ID                 int64              `json:"id"`
	OrderID            int64              `json:"order_id"`
	PaymentID          pgtype.Int8        `json:"payment_id"`
	IdempotencyKey     pgtype.Text        `json:"idempotency_key"`
	Provider           string             `json:"provider"`
	MerchantTradeNo    string             `json:"merchant_trade_no"`
	ProviderTradeNo    pgtype.Text        `json:"provider_trade_no"`
	Method             string             `json:"method"`
	Amount             int64              `json:"amount"`
	Status             int16              `json:"status"`
	RequestPayload     []byte             `json:"request_payload"`
	ResponsePayload    []byte             `json:"response_payload"`
	CallbackPayload    []byte             `json:"callback_payload"`
	FailureReason      pgtype.Text        `json:"failure_reason"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	SucceededAt        pgtype.Timestamptz `json:"succeeded_at"`
	FailedAt           pgtype.Timestamptz `json:"failed_at"`
	ReconcileAttempts  int32              `json:"reconcile_attempts"`
	NextReconcileAt    pgtype.Timestamptz `json:"next_reconcile_at"`
	LastReconcileError pgtype.Text        `json:"last_reconcile_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPaymentAttemptByIdempotencyKey(ctx context.Context, arg GetPaymentAttemptByIdempotencyKeyParams) (GetPaymentAttemptByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptByIdempotencyKey, arg.OrderID, arg.IdempotencyKey)
	var i GetPaymentAttemptByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.Provider,
		&i.MerchantTradeNo,
		&i.ProviderTradeNo,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.CallbackPayload,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.SucceededAt,
		&i.FailedAt,
		&i.ReconcileAttempts,
		&i.NextReconcileAt,
		&i.LastReconcileError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentAttemptByMerchantTradeNo = `-- name: GetPaymentAttemptByMerchantTradeNo :one
SELECT
    id,
    order_id,
    payment_id,
    idempotency_key,
    provider,
    merchant_trade_no,
    provider_trade_no,
    method,
    amount,
    status,
    request_payload,
    response_payload,
    callback_payload,
    failure_reason,
    expires_at,
    succeeded_at,
    failed_at,
    reconcile_attempts,
    next_reconcile_at,
    last_reconcile_error,
    created_at,
    updated_at
FROM payment_attempts
WHERE merchant_trade_no = $1
LIMIT 1
`

type GetPaymentAttemptByMerchantTradeNoRow struct {
	ID                 int64              `json:"id"`
	OrderID            int64              `json:"order_id"`
	PaymentID          pgtype.Int8        `json:"payment_id"`
	IdempotencyKey     pgtype.Text        `json:"idempotency_key"`
	Provider           string             `json:"provider"`
	MerchantTradeNo    string             `json:"merchant_trade_no"`
	ProviderTradeNo    pgtype.Text        `json:"provider_trade_no"`
	Method             string             `json:"method"`
	Amount             int64              `json:"amount"`
	Status             int16              `json:"status"`
	RequestPayload     []byte             `json:"request_payload"`
	ResponsePayload    []byte             `json:"response_payload"`
	CallbackPayload    []byte             `json:"callback_payload"`
	FailureReason      pgtype.Text        `json:"failure_reason"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	SucceededAt        pgtype.Timestamptz `json:"succeeded_at"`
	FailedAt           pgtype.Timestamptz `json:"failed_at"`
	ReconcileAttempts  int32              `json:"reconcile_attempts"`
	NextReconcileAt    pgtype.Timestamptz `json:"next_reconcile_at"`
	LastReconcileError pgtype.Text        `json:"last_reconcile_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPaymentAttemptByMerchantTradeNo(ctx context.Context, merchantTradeNo string) (GetPaymentAttemptByMerchantTradeNoRow, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptByMerchantTradeNo, merchantTradeNo)
	var i GetPaymentAttemptByMerchantTradeNoRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.Provider,
		&i.MerchantTradeNo,
		&i.ProviderTradeNo,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.CallbackPayload,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.SucceededAt,
		&i.FailedAt,
		&i.ReconcileAttempts,
		&i.NextReconcileAt,
		&i.LastReconcileError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentAttemptsByOrderID = `-- name: ListPaymentAttemptsByOrderID :many
SELECT
    id,
    order_id,
    payment_id,
    idempotency_key,
    provider,
    merchant_trade_no,
    provider_trade_no,
    method,
    amount,
    status,
    request_payload,
    response_payload,
    callback_payload,
    failure_reason,
    expires_at,
    succeeded_at,
    failed_at,
    reconcile_attempts,
    next_reconcile_at,
    last_reconcile_error,
    created_at,
    updated_at
FROM payment_attempts
WHERE order_id = $1
ORDER BY created_at DESC, id DESC
`

type ListPaymentAttemptsByOrderIDRow struct {
	ID                 int64              `json:"id"`
	OrderID            int64              `json:"order_id"`
	PaymentID          pgtype.Int8        `json:"payment_id"`
	IdempotencyKey     pgtype.Text        `json:"idempotency_key"`
	Provider           string             `json:"provider"`
	MerchantTradeNo    string             `json:"merchant_trade_no"`
	ProviderTradeNo    pgtype.Text        `json:"provider_trade_no"`
	Method             string             `json:"method"`
	Amount             int64              `json:"amount"`
	Status             int16              `json:"status"`
	RequestPayload     []byte             `json:"request_payload"`
	ResponsePayload    []byte             `json:"response_payload"`
	CallbackPayload    []byte             `json:"callback_payload"`
	FailureReason      pgtype.Text        `json:"failure_reason"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	SucceededAt        pgtype.Timestamptz `json:"succeeded_at"`
	FailedAt           pgtype.Timestamptz `json:"failed_at"`
	ReconcileAttempts  int32              `json:"reconcile_attempts"`
	NextReconcileAt    pgtype.Timestamptz `json:"next_reconcile_at"`
	LastReconcileError pgtype.Text        `json:"last_reconcile_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPaymentAttemptsByOrderID(ctx context.Context, orderID int64) ([]ListPaymentAttemptsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, listPaymentAttemptsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentAttemptsByOrderIDRow{}
	for rows.Next() {
		var i ListPaymentAttemptsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.PaymentID,
			&i.IdempotencyKey,
			&i.Provider,
			&i.MerchantTradeNo,
			&i.ProviderTradeNo,
			&i.Method,
			&i.Amount,
			&i.Status,
			&i.RequestPayload,
			&i.ResponsePayload,
			&i.CallbackPayload,
			&i.FailureReason,
			&i.ExpiresAt,
			&i.SucceededAt,
			&i.FailedAt,
			&i.ReconcileAttempts,
			&i.NextReconcileAt,
			&i.LastReconcileError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentAttemptsForReconciliation = `-- name: ListPaymentAttemptsForReconciliation :many
SELECT
    id,
    order_id,
    payment_id,
    idempotency_key,
    provider,
    merchant_trade_no,
    provider_trade_no,
    method,
    amount,
    status,
    request_payload,
    response_payload,
    callback_payload,
    failure_reason,
    expires_at,
    succeeded_at,
    failed_at,
    reconcile_attempts,
    next_reconcile_at,
    last_reconcile_error,
    created_at,
    updated_at
FROM payment_attempts
WHERE status IN (1, 4)
  AND reconcile_attempts < $1::integer
  AND (
      next_reconcile_at IS NULL
      OR next_reconcile_at <= $2::timestamptz
  )
  AND created_at <= $3::timestamptz
ORDER BY created_at ASC, id ASC
LIMIT $4::integer
`

type ListPaymentAttemptsForReconciliationParams struct {
	MaxAttempts int32              `json:"max_attempts"`
	Now         pgtype.Timestamptz `json:"now"`
	Cutoff      pgtype.Timestamptz `json:"cutoff"`
	LimitRows   int32              `json:"limit_rows"`
}

type ListPaymentAttemptsForReconciliationRow struct {
	ID                 int64              `json:"id"`
	OrderID            int64              `json:"order_id"`
	PaymentID          pgtype.Int8        `json:"payment_id"`
	IdempotencyKey     pgtype.Text        `json:"idempotency_key"`
	Provider           string             `json:"provider"`
	MerchantTradeNo    string             `json:"merchant_trade_no"`
	ProviderTradeNo    pgtype.Text        `json:"provider_trade_no"`
	Method             string             `json:"method"`
	Amount             int64              `json:"amount"`
	Status             int16              `json:"status"`
	RequestPayload     []byte             `json:"request_payload"`
	ResponsePayload    []byte             `json:"response_payload"`
	CallbackPayload    []byte             `json:"callback_payload"`
	FailureReason      pgtype.Text        `json:"failure_reason"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	SucceededAt        pgtype.Timestamptz `json:"succeeded_at"`
	FailedAt           pgtype.Timestamptz `json:"failed_at"`
	ReconcileAttempts  int32              `json:"reconcile_attempts"`
	NextReconcileAt    pgtype.Timestamptz `json:"next_reconcile_at"`
	LastReconcileError pgtype.Text        `json:"last_reconcile_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPaymentAttemptsForReconciliation(ctx context.Context, arg ListPaymentAttemptsForReconciliationParams) ([]ListPaymentAttemptsForReconciliationRow, error) {
	rows, err := q.db.Query(ctx, listPaymentAttemptsForReconciliation,
		arg.MaxAttempts,
		arg.Now,
		arg.Cutoff,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentAttemptsForReconciliationRow{}
	for rows.Next() {
		var i ListPaymentAttemptsForReconciliationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.PaymentID,
			&i.IdempotencyKey,
			&i.Provider,
			&i.MerchantTradeNo,
			&i.ProviderTradeNo,
			&i.Method,
			&i.Amount,
			&i.Status,
			&i.RequestPayload,
			&i.ResponsePayload,
			&i.CallbackPayload,
			&i.FailureReason,
			&i.ExpiresAt,
			&i.SucceededAt,
			&i.FailedAt,
			&i.ReconcileAttempts,
			&i.NextReconcileAt,
			&i.LastReconcileError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentAttemptStatus = `-- name: UpdatePaymentAttemptStatus :exec
UPDATE payment_attempts
SET
    payment_id = $2,
    provider_trade_no = $3,
    status = $4,
    response_payload = $5,
    callback_payload = $6,
    failure_reason = $7,
    succeeded_at = $8,
    failed_at = $9,
    reconcile_attempts = $10,
    next_reconcile_at = $11,
    last_reconcile_error = $12,
    updated_at = $13
WHERE id = $1
`

type UpdatePaymentAttemptStatusParams struct {
	ID                 int64              `json:"id"`
	PaymentID          pgtype.Int8        `json:"payment_id"`
	ProviderTradeNo    pgtype.Text        `json:"provider_trade_no"`
	Status             int16              `json:"status"`
	ResponsePayload    []byte             `json:"response_payload"`
	CallbackPayload    []byte             `json:"callback_payload"`
	FailureReason      pgtype.Text        `json:"failure_reason"`
	SucceededAt        pgtype.Timestamptz `json:"succeeded_at"`
	FailedAt           pgtype.Timestamptz `json:"failed_at"`
	ReconcileAttempts  int32              `json:"reconcile_attempts"`
	NextReconcileAt    pgtype.Timestamptz `json:"next_reconcile_at"`
	LastReconcileError pgtype.Text        `json:"last_reconcile_error"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePaymentAttemptStatus(ctx context.Context, arg UpdatePaymentAttemptStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentAttemptStatus,
		arg.ID,
		arg.PaymentID,
		arg.ProviderTradeNo,
		arg.Status,
		arg.ResponsePayload,
		arg.CallbackPayload,
		arg.FailureReason,
		arg.SucceededAt,
		arg.FailedAt,
		arg.ReconcileAttempts,
		arg.NextReconcileAt,
		arg.LastReconcileError,
		arg.UpdatedAt,
	)
	return err
}
