// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_attempt.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentAttempt = `-- name: CreatePaymentAttempt :one
INSERT INTO payment_attempts (
    order_id,
    payment_id,
    idempotency_key,
    provider,
    merchant_trade_no,
    provider_trade_no,
    method,
    amount,
    status,
    request_payload,
    response_payload,
    callback_payload,
    failure_reason,
    expires_at,
    succeeded_at,
    failed_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $17
)
RETURNING
    id,
    order_id,
    payment_id,
    idempotency_key,
    provider,
    merchant_trade_no,
    provider_trade_no,
    method,
    amount,
    status,
    request_payload,
    response_payload,
    callback_payload,
    failure_reason,
    expires_at,
    succeeded_at,
    failed_at,
    created_at,
    updated_at
`

type CreatePaymentAttemptParams struct {
	OrderID         int64              `json:"order_id"`
	PaymentID       pgtype.Int8        `json:"payment_id"`
	IdempotencyKey  pgtype.Text        `json:"idempotency_key"`
	Provider        string             `json:"provider"`
	MerchantTradeNo string             `json:"merchant_trade_no"`
	ProviderTradeNo pgtype.Text        `json:"provider_trade_no"`
	Method          string             `json:"method"`
	Amount          int64              `json:"amount"`
	Status          int16              `json:"status"`
	RequestPayload  []byte             `json:"request_payload"`
	ResponsePayload []byte             `json:"response_payload"`
	CallbackPayload []byte             `json:"callback_payload"`
	FailureReason   pgtype.Text        `json:"failure_reason"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	SucceededAt     pgtype.Timestamptz `json:"succeeded_at"`
	FailedAt        pgtype.Timestamptz `json:"failed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePaymentAttempt(ctx context.Context, arg CreatePaymentAttemptParams) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, createPaymentAttempt,
		arg.OrderID,
		arg.PaymentID,
		arg.IdempotencyKey,
		arg.Provider,
		arg.MerchantTradeNo,
		arg.ProviderTradeNo,
		arg.Method,
		arg.Amount,
		arg.Status,
		arg.RequestPayload,
		arg.ResponsePayload,
		arg.CallbackPayload,
		arg.FailureReason,
		arg.ExpiresAt,
		arg.SucceededAt,
		arg.FailedAt,
		arg.CreatedAt,
	)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.Provider,
		&i.MerchantTradeNo,
		&i.ProviderTradeNo,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.CallbackPayload,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.SucceededAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentAttemptByIdempotencyKey = `-- name: GetPaymentAttemptByIdempotencyKey :one
SELECT
    id,
    order_id,
    payment_id,
    idempotency_key,
    provider,
    merchant_trade_no,
    provider_trade_no,
    method,
    amount,
    status,
    request_payload,
    response_payload,
    callback_payload,
    failure_reason,
    expires_at,
    succeeded_at,
    failed_at,
    created_at,
    updated_at
FROM payment_attempts
WHERE idempotency_key = $1
LIMIT 1
`

func (q *Queries) GetPaymentAttemptByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptByIdempotencyKey, idempotencyKey)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.Provider,
		&i.MerchantTradeNo,
		&i.ProviderTradeNo,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.CallbackPayload,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.SucceededAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentAttemptByMerchantTradeNo = `-- name: GetPaymentAttemptByMerchantTradeNo :one
SELECT
    id,
    order_id,
    payment_id,
    idempotency_key,
    provider,
    merchant_trade_no,
    provider_trade_no,
    method,
    amount,
    status,
    request_payload,
    response_payload,
    callback_payload,
    failure_reason,
    expires_at,
    succeeded_at,
    failed_at,
    created_at,
    updated_at
FROM payment_attempts
WHERE merchant_trade_no = $1
LIMIT 1
`

func (q *Queries) GetPaymentAttemptByMerchantTradeNo(ctx context.Context, merchantTradeNo string) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptByMerchantTradeNo, merchantTradeNo)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.Provider,
		&i.MerchantTradeNo,
		&i.ProviderTradeNo,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.CallbackPayload,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.SucceededAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentAttemptsByOrderID = `-- name: ListPaymentAttemptsByOrderID :many
SELECT
    id,
    order_id,
    payment_id,
    idempotency_key,
    provider,
    merchant_trade_no,
    provider_trade_no,
    method,
    amount,
    status,
    request_payload,
    response_payload,
    callback_payload,
    failure_reason,
    expires_at,
    succeeded_at,
    failed_at,
    created_at,
    updated_at
FROM payment_attempts
WHERE order_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPaymentAttemptsByOrderID(ctx context.Context, orderID int64) ([]PaymentAttempt, error) {
	rows, err := q.db.Query(ctx, listPaymentAttemptsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentAttempt{}
	for rows.Next() {
		var i PaymentAttempt
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.PaymentID,
			&i.IdempotencyKey,
			&i.Provider,
			&i.MerchantTradeNo,
			&i.ProviderTradeNo,
			&i.Method,
			&i.Amount,
			&i.Status,
			&i.RequestPayload,
			&i.ResponsePayload,
			&i.CallbackPayload,
			&i.FailureReason,
			&i.ExpiresAt,
			&i.SucceededAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentAttemptStatus = `-- name: UpdatePaymentAttemptStatus :exec
UPDATE payment_attempts
SET
    payment_id = $2,
    provider_trade_no = $3,
    status = $4,
    response_payload = $5,
    callback_payload = $6,
    failure_reason = $7,
    succeeded_at = $8,
    failed_at = $9,
    updated_at = $10
WHERE id = $1
`

type UpdatePaymentAttemptStatusParams struct {
	ID              int64              `json:"id"`
	PaymentID       pgtype.Int8        `json:"payment_id"`
	ProviderTradeNo pgtype.Text        `json:"provider_trade_no"`
	Status          int16              `json:"status"`
	ResponsePayload []byte             `json:"response_payload"`
	CallbackPayload []byte             `json:"callback_payload"`
	FailureReason   pgtype.Text        `json:"failure_reason"`
	SucceededAt     pgtype.Timestamptz `json:"succeeded_at"`
	FailedAt        pgtype.Timestamptz `json:"failed_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePaymentAttemptStatus(ctx context.Context, arg UpdatePaymentAttemptStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentAttemptStatus,
		arg.ID,
		arg.PaymentID,
		arg.ProviderTradeNo,
		arg.Status,
		arg.ResponsePayload,
		arg.CallbackPayload,
		arg.FailureReason,
		arg.SucceededAt,
		arg.FailedAt,
		arg.UpdatedAt,
	)
	return err
}
