// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	CreateSection(ctx context.Context, arg CreateSectionParams) (EventSection, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetActiveReservationByUserAndEvent(ctx context.Context, arg GetActiveReservationByUserAndEventParams) (Reservation, error)
	GetEventByID(ctx context.Context, id int64) (Event, error)
	GetOrderByID(ctx context.Context, id int64) (Order, error)
	GetOrderByOrderNo(ctx context.Context, orderNo string) (Order, error)
	GetPaymentByPaymentNo(ctx context.Context, paymentNo string) (Payment, error)
	GetReservationByID(ctx context.Context, id int64) (Reservation, error)
	GetReservationByReservationNo(ctx context.Context, reservationNo string) (Reservation, error)
	GetSectionByEventAndID(ctx context.Context, arg GetSectionByEventAndIDParams) (EventSection, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	ListEvents(ctx context.Context) ([]Event, error)
	ListExpiredHoldingReservations(ctx context.Context, arg ListExpiredHoldingReservationsParams) ([]Reservation, error)
	ListExpiredPendingOrders(ctx context.Context, arg ListExpiredPendingOrdersParams) ([]Order, error)
	ListOrdersByUserID(ctx context.Context, userID int64) ([]Order, error)
	ListPaymentsByUserID(ctx context.Context, userID int64) ([]Payment, error)
	ListReservationsByUserID(ctx context.Context, userID int64) ([]Reservation, error)
	ListSectionsByEventID(ctx context.Context, eventID int64) ([]EventSection, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
	UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) error
	UpdateSectionInventory(ctx context.Context, arg UpdateSectionInventoryParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
