// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET
    status = $3,
    response_status = $4,
    response_body = $5,
    locked_until = NULL,
    updated_at = $6
WHERE key = $1
  AND endpoint = $2
`

type CompleteIdempotencyKeyParams struct {
	Key            string             `json:"key"`
	Endpoint       string             `json:"endpoint"`
	Status         int16              `json:"status"`
	ResponseStatus pgtype.Int4        `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.Key,
		arg.Endpoint,
		arg.Status,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.UpdatedAt,
	)
	return err
}

const confirmSectionSale = `-- name: ConfirmSectionSale :one
UPDATE event_sections
SET
    reserved_quantity = reserved_quantity - $1::integer,
    sold_quantity = sold_quantity + $1::integer,
    status = CASE
        WHEN total_quantity - (reserved_quantity - $1::integer) - (sold_quantity + $1::integer) = 0 THEN 3
        ELSE status
    END,
    updated_at = $2
WHERE event_id = $3
  AND id = $4
  AND $1::integer > 0
  AND reserved_quantity >= $1::integer
RETURNING
    id,
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status,
    created_at,
    updated_at
`

type ConfirmSectionSaleParams struct {
	Quantity  int32              `json:"quantity"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	EventID   int64              `json:"event_id"`
	ID        int64              `json:"id"`
}

func (q *Queries) ConfirmSectionSale(ctx context.Context, arg ConfirmSectionSaleParams) (EventSection, error) {
	row := q.db.QueryRow(ctx, confirmSectionSale,
		arg.Quantity,
		arg.UpdatedAt,
		arg.EventID,
		arg.ID,
	)
	var i EventSection
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventName,
		&i.SectionName,
		&i.Price,
		&i.TotalQuantity,
		&i.ReservedQuantity,
		&i.SoldQuantity,
		&i.PurchaseLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAdminAuditLog = `-- name: CreateAdminAuditLog :one
INSERT INTO admin_audit_logs (
    admin_user_id,
    action,
    target_type,
    target_id,
    reason,
    ip_address,
    user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING
    id,
    admin_user_id,
    action,
    target_type,
    target_id,
    reason,
    ip_address,
    user_agent,
    created_at
`

type CreateAdminAuditLogParams struct {
	AdminUserID int64       `json:"admin_user_id"`
	Action      string      `json:"action"`
	TargetType  string      `json:"target_type"`
	TargetID    int64       `json:"target_id"`
	Reason      pgtype.Text `json:"reason"`
	IpAddress   pgtype.Text `json:"ip_address"`
	UserAgent   pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateAdminAuditLog(ctx context.Context, arg CreateAdminAuditLogParams) (AdminAuditLog, error) {
	row := q.db.QueryRow(ctx, createAdminAuditLog,
		arg.AdminUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Reason,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AdminAuditLog
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (
    organizer_id,
    name,
    email,
    password_hash,
    role,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING
    id,
    organizer_id,
    name,
    email,
    password_hash,
    role,
    status,
    created_at,
    updated_at
`

type CreateAdminUserParams struct {
	OrganizerID  pgtype.Int8 `json:"organizer_id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Role         string      `json:"role"`
	Status       int16       `json:"status"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdminUser,
		arg.OrganizerID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
	)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    organizer_id,
    name,
    venue,
    status,
    start_at,
    end_at,
    sale_start_at,
    sale_end_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING
    id,
    organizer_id,
    name,
    venue,
    status,
    start_at,
    end_at,
    sale_start_at,
    sale_end_at,
    created_at,
    updated_at
`

type CreateEventParams struct {
	OrganizerID int64              `json:"organizer_id"`
	Name        string             `json:"name"`
	Venue       string             `json:"venue"`
	Status      int16              `json:"status"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	SaleStartAt pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt   pgtype.Timestamptz `json:"sale_end_at"`
}

type CreateEventRow struct {
	ID          int64              `json:"id"`
	OrganizerID int64              `json:"organizer_id"`
	Name        string             `json:"name"`
	Venue       string             `json:"venue"`
	Status      int16              `json:"status"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	SaleStartAt pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt   pgtype.Timestamptz `json:"sale_end_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.OrganizerID,
		arg.Name,
		arg.Venue,
		arg.Status,
		arg.StartAt,
		arg.EndAt,
		arg.SaleStartAt,
		arg.SaleEndAt,
	)
	var i CreateEventRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Venue,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.SaleStartAt,
		&i.SaleEndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (
    key,
    user_id,
    endpoint,
    request_hash,
    status,
    locked_until,
    expires_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $8
)
RETURNING
    id,
    key,
    user_id,
    endpoint,
    request_hash,
    status,
    response_status,
    response_body,
    locked_until,
    expires_at,
    created_at,
    updated_at
`

type CreateIdempotencyKeyParams struct {
	Key         string             `json:"key"`
	UserID      pgtype.Int8        `json:"user_id"`
	Endpoint    string             `json:"endpoint"`
	RequestHash string             `json:"request_hash"`
	Status      int16              `json:"status"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.Key,
		arg.UserID,
		arg.Endpoint,
		arg.RequestHash,
		arg.Status,
		arg.LockedUntil,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserID,
		&i.Endpoint,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LockedUntil,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING
    id,
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
`

type CreateOrderParams struct {
	OrderNo       string             `json:"order_no"`
	ReservationID int64              `json:"reservation_id"`
	ReservationNo string             `json:"reservation_no"`
	EventID       int64              `json:"event_id"`
	EventName     string             `json:"event_name"`
	SectionID     int64              `json:"section_id"`
	SectionName   string             `json:"section_name"`
	UserID        int64              `json:"user_id"`
	UserName      string             `json:"user_name"`
	Quantity      int32              `json:"quantity"`
	UnitPrice     int64              `json:"unit_price"`
	TotalAmount   int64              `json:"total_amount"`
	Status        int16              `json:"status"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderNo,
		arg.ReservationID,
		arg.ReservationNo,
		arg.EventID,
		arg.EventName,
		arg.SectionID,
		arg.SectionName,
		arg.UserID,
		arg.UserName,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalAmount,
		arg.Status,
		arg.ExpiresAt,
		arg.PaidAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.ReservationID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    payment_no,
    order_id,
    order_no,
    reservation_id,
    event_id,
    event_name,
    user_id,
    user_name,
    method,
    amount,
    status,
    paid_at,
    failed_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING
    id,
    payment_no,
    order_id,
    order_no,
    reservation_id,
    event_id,
    event_name,
    user_id,
    user_name,
    method,
    amount,
    status,
    paid_at,
    failed_at,
    created_at,
    updated_at
`

type CreatePaymentParams struct {
	PaymentNo     string             `json:"payment_no"`
	OrderID       int64              `json:"order_id"`
	OrderNo       string             `json:"order_no"`
	ReservationID int64              `json:"reservation_id"`
	EventID       int64              `json:"event_id"`
	EventName     string             `json:"event_name"`
	UserID        int64              `json:"user_id"`
	UserName      string             `json:"user_name"`
	Method        string             `json:"method"`
	Amount        int64              `json:"amount"`
	Status        int16              `json:"status"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	FailedAt      pgtype.Timestamptz `json:"failed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.PaymentNo,
		arg.OrderID,
		arg.OrderNo,
		arg.ReservationID,
		arg.EventID,
		arg.EventName,
		arg.UserID,
		arg.UserName,
		arg.Method,
		arg.Amount,
		arg.Status,
		arg.PaidAt,
		arg.FailedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.OrderNo,
		&i.ReservationID,
		&i.EventID,
		&i.EventName,
		&i.UserID,
		&i.UserName,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.PaidAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentAttempt = `-- name: CreatePaymentAttempt :one
INSERT INTO payment_attempts (
    order_id,
    payment_id,
    idempotency_key,
    provider,
    merchant_trade_no,
    provider_trade_no,
    method,
    amount,
    status,
    request_payload,
    response_payload,
    callback_payload,
    failure_reason,
    expires_at,
    succeeded_at,
    failed_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $17
)
RETURNING
    id,
    order_id,
    payment_id,
    idempotency_key,
    provider,
    merchant_trade_no,
    provider_trade_no,
    method,
    amount,
    status,
    request_payload,
    response_payload,
    callback_payload,
    failure_reason,
    expires_at,
    succeeded_at,
    failed_at,
    created_at,
    updated_at
`

type CreatePaymentAttemptParams struct {
	OrderID         int64              `json:"order_id"`
	PaymentID       pgtype.Int8        `json:"payment_id"`
	IdempotencyKey  pgtype.Text        `json:"idempotency_key"`
	Provider        string             `json:"provider"`
	MerchantTradeNo string             `json:"merchant_trade_no"`
	ProviderTradeNo pgtype.Text        `json:"provider_trade_no"`
	Method          string             `json:"method"`
	Amount          int64              `json:"amount"`
	Status          int16              `json:"status"`
	RequestPayload  []byte             `json:"request_payload"`
	ResponsePayload []byte             `json:"response_payload"`
	CallbackPayload []byte             `json:"callback_payload"`
	FailureReason   pgtype.Text        `json:"failure_reason"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	SucceededAt     pgtype.Timestamptz `json:"succeeded_at"`
	FailedAt        pgtype.Timestamptz `json:"failed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePaymentAttempt(ctx context.Context, arg CreatePaymentAttemptParams) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, createPaymentAttempt,
		arg.OrderID,
		arg.PaymentID,
		arg.IdempotencyKey,
		arg.Provider,
		arg.MerchantTradeNo,
		arg.ProviderTradeNo,
		arg.Method,
		arg.Amount,
		arg.Status,
		arg.RequestPayload,
		arg.ResponsePayload,
		arg.CallbackPayload,
		arg.FailureReason,
		arg.ExpiresAt,
		arg.SucceededAt,
		arg.FailedAt,
		arg.CreatedAt,
	)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.Provider,
		&i.MerchantTradeNo,
		&i.ProviderTradeNo,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.CallbackPayload,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.SucceededAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
`

type CreateReservationParams struct {
	ReservationNo string             `json:"reservation_no"`
	EventID       int64              `json:"event_id"`
	EventName     string             `json:"event_name"`
	SectionID     int64              `json:"section_id"`
	SectionName   string             `json:"section_name"`
	UserID        int64              `json:"user_id"`
	UserName      string             `json:"user_name"`
	Quantity      int32              `json:"quantity"`
	UnitPrice     int64              `json:"unit_price"`
	TotalAmount   int64              `json:"total_amount"`
	Status        int16              `json:"status"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.ReservationNo,
		arg.EventID,
		arg.EventName,
		arg.SectionID,
		arg.SectionName,
		arg.UserID,
		arg.UserName,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalAmount,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSection = `-- name: CreateSection :one
INSERT INTO event_sections (
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING
    id,
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status,
    created_at,
    updated_at
`

type CreateSectionParams struct {
	EventID          int64  `json:"event_id"`
	EventName        string `json:"event_name"`
	SectionName      string `json:"section_name"`
	Price            int64  `json:"price"`
	TotalQuantity    int32  `json:"total_quantity"`
	ReservedQuantity int32  `json:"reserved_quantity"`
	SoldQuantity     int32  `json:"sold_quantity"`
	PurchaseLimit    int32  `json:"purchase_limit"`
	Status           int16  `json:"status"`
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (EventSection, error) {
	row := q.db.QueryRow(ctx, createSection,
		arg.EventID,
		arg.EventName,
		arg.SectionName,
		arg.Price,
		arg.TotalQuantity,
		arg.ReservedQuantity,
		arg.SoldQuantity,
		arg.PurchaseLimit,
		arg.Status,
	)
	var i EventSection
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventName,
		&i.SectionName,
		&i.Price,
		&i.TotalQuantity,
		&i.ReservedQuantity,
		&i.SoldQuantity,
		&i.PurchaseLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name,
    email,
    password_hash
) VALUES (
    $1, $2, $3
)
RETURNING
    id,
    name,
    email,
    password_hash,
    created_at,
    updated_at
`

type CreateUserParams struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveReservationByUserAndEvent = `-- name: GetActiveReservationByUserAndEvent :one
SELECT
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE user_id = $1
  AND event_id = $2
  AND status = 1
  AND expires_at > $3
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetActiveReservationByUserAndEventParams struct {
	UserID    int64              `json:"user_id"`
	EventID   int64              `json:"event_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetActiveReservationByUserAndEvent(ctx context.Context, arg GetActiveReservationByUserAndEventParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, getActiveReservationByUserAndEvent, arg.UserID, arg.EventID, arg.ExpiresAt)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminUserByEmail = `-- name: GetAdminUserByEmail :one
SELECT
    id,
    organizer_id,
    name,
    email,
    password_hash,
    role,
    status,
    created_at,
    updated_at
FROM admin_users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUserByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminUserByID = `-- name: GetAdminUserByID :one
SELECT
    id,
    organizer_id,
    name,
    email,
    password_hash,
    role,
    status,
    created_at,
    updated_at
FROM admin_users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAdminUserByID(ctx context.Context, id int64) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUserByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT
    id,
    organizer_id,
    name,
    venue,
    status,
    start_at,
    end_at,
    sale_start_at,
    sale_end_at,
    created_at,
    updated_at
FROM events
WHERE id = $1
LIMIT 1
`

type GetEventByIDRow struct {
	ID          int64              `json:"id"`
	OrganizerID int64              `json:"organizer_id"`
	Name        string             `json:"name"`
	Venue       string             `json:"venue"`
	Status      int16              `json:"status"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	SaleStartAt pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt   pgtype.Timestamptz `json:"sale_end_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEventByID(ctx context.Context, id int64) (GetEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Venue,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.SaleStartAt,
		&i.SaleEndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT
    id,
    key,
    user_id,
    endpoint,
    request_hash,
    status,
    response_status,
    response_body,
    locked_until,
    expires_at,
    created_at,
    updated_at
FROM idempotency_keys
WHERE key = $1
  AND endpoint = $2
LIMIT 1
`

type GetIdempotencyKeyParams struct {
	Key      string `json:"key"`
	Endpoint string `json:"endpoint"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.Key, arg.Endpoint)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserID,
		&i.Endpoint,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.LockedUntil,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
    id,
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
FROM orders
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.ReservationID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByOrderNo = `-- name: GetOrderByOrderNo :one
SELECT
    id,
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
FROM orders
WHERE order_no = $1
LIMIT 1
`

func (q *Queries) GetOrderByOrderNo(ctx context.Context, orderNo string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByOrderNo, orderNo)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.ReservationID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentAttemptByIdempotencyKey = `-- name: GetPaymentAttemptByIdempotencyKey :one
SELECT
    id,
    order_id,
    payment_id,
    idempotency_key,
    provider,
    merchant_trade_no,
    provider_trade_no,
    method,
    amount,
    status,
    request_payload,
    response_payload,
    callback_payload,
    failure_reason,
    expires_at,
    succeeded_at,
    failed_at,
    created_at,
    updated_at
FROM payment_attempts
WHERE idempotency_key = $1
LIMIT 1
`

func (q *Queries) GetPaymentAttemptByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptByIdempotencyKey, idempotencyKey)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.Provider,
		&i.MerchantTradeNo,
		&i.ProviderTradeNo,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.CallbackPayload,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.SucceededAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentAttemptByMerchantTradeNo = `-- name: GetPaymentAttemptByMerchantTradeNo :one
SELECT
    id,
    order_id,
    payment_id,
    idempotency_key,
    provider,
    merchant_trade_no,
    provider_trade_no,
    method,
    amount,
    status,
    request_payload,
    response_payload,
    callback_payload,
    failure_reason,
    expires_at,
    succeeded_at,
    failed_at,
    created_at,
    updated_at
FROM payment_attempts
WHERE merchant_trade_no = $1
LIMIT 1
`

func (q *Queries) GetPaymentAttemptByMerchantTradeNo(ctx context.Context, merchantTradeNo string) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptByMerchantTradeNo, merchantTradeNo)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentID,
		&i.IdempotencyKey,
		&i.Provider,
		&i.MerchantTradeNo,
		&i.ProviderTradeNo,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.CallbackPayload,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.SucceededAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByPaymentNo = `-- name: GetPaymentByPaymentNo :one
SELECT
    id,
    payment_no,
    order_id,
    order_no,
    reservation_id,
    event_id,
    event_name,
    user_id,
    user_name,
    method,
    amount,
    status,
    paid_at,
    failed_at,
    created_at,
    updated_at
FROM payments
WHERE payment_no = $1
LIMIT 1
`

func (q *Queries) GetPaymentByPaymentNo(ctx context.Context, paymentNo string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByPaymentNo, paymentNo)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.OrderNo,
		&i.ReservationID,
		&i.EventID,
		&i.EventName,
		&i.UserID,
		&i.UserName,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.PaidAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetReservationByID(ctx context.Context, id int64) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByID, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationByReservationNo = `-- name: GetReservationByReservationNo :one
SELECT
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE reservation_no = $1
LIMIT 1
`

func (q *Queries) GetReservationByReservationNo(ctx context.Context, reservationNo string) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByReservationNo, reservationNo)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSectionByEventAndID = `-- name: GetSectionByEventAndID :one
SELECT
    id,
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status,
    created_at,
    updated_at
FROM event_sections
WHERE event_id = $1
  AND id = $2
LIMIT 1
`

type GetSectionByEventAndIDParams struct {
	EventID int64 `json:"event_id"`
	ID      int64 `json:"id"`
}

func (q *Queries) GetSectionByEventAndID(ctx context.Context, arg GetSectionByEventAndIDParams) (EventSection, error) {
	row := q.db.QueryRow(ctx, getSectionByEventAndID, arg.EventID, arg.ID)
	var i EventSection
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventName,
		&i.SectionName,
		&i.Price,
		&i.TotalQuantity,
		&i.ReservedQuantity,
		&i.SoldQuantity,
		&i.PurchaseLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    name,
    email,
    password_hash,
    created_at,
    updated_at
FROM users
WHERE email = $1
LIMIT 1
`

type GetUserByEmailRow struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    name,
    email,
    password_hash,
    created_at,
    updated_at
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT
    id,
    organizer_id,
    name,
    venue,
    status,
    start_at,
    end_at,
    sale_start_at,
    sale_end_at,
    created_at,
    updated_at
FROM events
ORDER BY id
`

type ListEventsRow struct {
	ID          int64              `json:"id"`
	OrganizerID int64              `json:"organizer_id"`
	Name        string             `json:"name"`
	Venue       string             `json:"venue"`
	Status      int16              `json:"status"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	SaleStartAt pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt   pgtype.Timestamptz `json:"sale_end_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListEvents(ctx context.Context) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Name,
			&i.Venue,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.SaleStartAt,
			&i.SaleEndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredHoldingReservations = `-- name: ListExpiredHoldingReservations :many
SELECT
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE status = 1
  AND expires_at <= $1
ORDER BY expires_at
LIMIT $2
`

type ListExpiredHoldingReservationsParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListExpiredHoldingReservations(ctx context.Context, arg ListExpiredHoldingReservationsParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listExpiredHoldingReservations, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.ReservationNo,
			&i.EventID,
			&i.EventName,
			&i.SectionID,
			&i.SectionName,
			&i.UserID,
			&i.UserName,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPendingOrders = `-- name: ListExpiredPendingOrders :many
SELECT
    id,
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
FROM orders
WHERE status = 1
  AND expires_at <= $1
ORDER BY expires_at
LIMIT $2
`

type ListExpiredPendingOrdersParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListExpiredPendingOrders(ctx context.Context, arg ListExpiredPendingOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingOrders, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.ReservationID,
			&i.ReservationNo,
			&i.EventID,
			&i.EventName,
			&i.SectionID,
			&i.SectionName,
			&i.UserID,
			&i.UserName,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Status,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT
    id,
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListOrdersByUserID(ctx context.Context, userID int64) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.ReservationID,
			&i.ReservationNo,
			&i.EventID,
			&i.EventName,
			&i.SectionID,
			&i.SectionName,
			&i.UserID,
			&i.UserName,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Status,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentAttemptsByOrderID = `-- name: ListPaymentAttemptsByOrderID :many
SELECT
    id,
    order_id,
    payment_id,
    idempotency_key,
    provider,
    merchant_trade_no,
    provider_trade_no,
    method,
    amount,
    status,
    request_payload,
    response_payload,
    callback_payload,
    failure_reason,
    expires_at,
    succeeded_at,
    failed_at,
    created_at,
    updated_at
FROM payment_attempts
WHERE order_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPaymentAttemptsByOrderID(ctx context.Context, orderID int64) ([]PaymentAttempt, error) {
	rows, err := q.db.Query(ctx, listPaymentAttemptsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentAttempt{}
	for rows.Next() {
		var i PaymentAttempt
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.PaymentID,
			&i.IdempotencyKey,
			&i.Provider,
			&i.MerchantTradeNo,
			&i.ProviderTradeNo,
			&i.Method,
			&i.Amount,
			&i.Status,
			&i.RequestPayload,
			&i.ResponsePayload,
			&i.CallbackPayload,
			&i.FailureReason,
			&i.ExpiresAt,
			&i.SucceededAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByUserID = `-- name: ListPaymentsByUserID :many
SELECT
    id,
    payment_no,
    order_id,
    order_no,
    reservation_id,
    event_id,
    event_name,
    user_id,
    user_name,
    method,
    amount,
    status,
    paid_at,
    failed_at,
    created_at,
    updated_at
FROM payments
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPaymentsByUserID(ctx context.Context, userID int64) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.PaymentNo,
			&i.OrderID,
			&i.OrderNo,
			&i.ReservationID,
			&i.EventID,
			&i.EventName,
			&i.UserID,
			&i.UserName,
			&i.Method,
			&i.Amount,
			&i.Status,
			&i.PaidAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByUserID = `-- name: ListReservationsByUserID :many
SELECT
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListReservationsByUserID(ctx context.Context, userID int64) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.ReservationNo,
			&i.EventID,
			&i.EventName,
			&i.SectionID,
			&i.SectionName,
			&i.UserID,
			&i.UserName,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByEventID = `-- name: ListSectionsByEventID :many
SELECT
    id,
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status,
    created_at,
    updated_at
FROM event_sections
WHERE event_id = $1
ORDER BY id
`

func (q *Queries) ListSectionsByEventID(ctx context.Context, eventID int64) ([]EventSection, error) {
	rows, err := q.db.Query(ctx, listSectionsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventSection{}
	for rows.Next() {
		var i EventSection
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventName,
			&i.SectionName,
			&i.Price,
			&i.TotalQuantity,
			&i.ReservedQuantity,
			&i.SoldQuantity,
			&i.PurchaseLimit,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseSectionInventory = `-- name: ReleaseSectionInventory :one
UPDATE event_sections
SET
    reserved_quantity = reserved_quantity - $1::integer,
    status = CASE
        WHEN status = 3 AND total_quantity - (reserved_quantity - $1::integer) - sold_quantity > 0 THEN 1
        ELSE status
    END,
    updated_at = $2
WHERE event_id = $3
  AND id = $4
  AND $1::integer > 0
  AND reserved_quantity >= $1::integer
RETURNING
    id,
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status,
    created_at,
    updated_at
`

type ReleaseSectionInventoryParams struct {
	Quantity  int32              `json:"quantity"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	EventID   int64              `json:"event_id"`
	ID        int64              `json:"id"`
}

func (q *Queries) ReleaseSectionInventory(ctx context.Context, arg ReleaseSectionInventoryParams) (EventSection, error) {
	row := q.db.QueryRow(ctx, releaseSectionInventory,
		arg.Quantity,
		arg.UpdatedAt,
		arg.EventID,
		arg.ID,
	)
	var i EventSection
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventName,
		&i.SectionName,
		&i.Price,
		&i.TotalQuantity,
		&i.ReservedQuantity,
		&i.SoldQuantity,
		&i.PurchaseLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveSectionInventory = `-- name: ReserveSectionInventory :one
UPDATE event_sections
SET
    reserved_quantity = reserved_quantity + $1::integer,
    updated_at = $2
WHERE event_id = $3
  AND id = $4
  AND status = 1
  AND $1::integer > 0
  AND (purchase_limit = 0 OR $1::integer <= purchase_limit)
  AND reserved_quantity + sold_quantity + $1::integer <= total_quantity
RETURNING
    id,
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status,
    created_at,
    updated_at
`

type ReserveSectionInventoryParams struct {
	Quantity  int32              `json:"quantity"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	EventID   int64              `json:"event_id"`
	ID        int64              `json:"id"`
}

func (q *Queries) ReserveSectionInventory(ctx context.Context, arg ReserveSectionInventoryParams) (EventSection, error) {
	row := q.db.QueryRow(ctx, reserveSectionInventory,
		arg.Quantity,
		arg.UpdatedAt,
		arg.EventID,
		arg.ID,
	)
	var i EventSection
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventName,
		&i.SectionName,
		&i.Price,
		&i.TotalQuantity,
		&i.ReservedQuantity,
		&i.SoldQuantity,
		&i.PurchaseLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET
    status = $2,
    paid_at = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID        int64              `json:"id"`
	Status    int16              `json:"status"`
	PaidAt    pgtype.Timestamptz `json:"paid_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus,
		arg.ID,
		arg.Status,
		arg.PaidAt,
		arg.UpdatedAt,
	)
	return err
}

const updatePaymentAttemptStatus = `-- name: UpdatePaymentAttemptStatus :exec
UPDATE payment_attempts
SET
    payment_id = $2,
    provider_trade_no = $3,
    status = $4,
    response_payload = $5,
    callback_payload = $6,
    failure_reason = $7,
    succeeded_at = $8,
    failed_at = $9,
    updated_at = $10
WHERE id = $1
`

type UpdatePaymentAttemptStatusParams struct {
	ID              int64              `json:"id"`
	PaymentID       pgtype.Int8        `json:"payment_id"`
	ProviderTradeNo pgtype.Text        `json:"provider_trade_no"`
	Status          int16              `json:"status"`
	ResponsePayload []byte             `json:"response_payload"`
	CallbackPayload []byte             `json:"callback_payload"`
	FailureReason   pgtype.Text        `json:"failure_reason"`
	SucceededAt     pgtype.Timestamptz `json:"succeeded_at"`
	FailedAt        pgtype.Timestamptz `json:"failed_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePaymentAttemptStatus(ctx context.Context, arg UpdatePaymentAttemptStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentAttemptStatus,
		arg.ID,
		arg.PaymentID,
		arg.ProviderTradeNo,
		arg.Status,
		arg.ResponsePayload,
		arg.CallbackPayload,
		arg.FailureReason,
		arg.SucceededAt,
		arg.FailedAt,
		arg.UpdatedAt,
	)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments
SET
    status = $2,
    paid_at = $3,
    failed_at = $4,
    updated_at = $5
WHERE id = $1
`

type UpdatePaymentStatusParams struct {
	ID        int64              `json:"id"`
	Status    int16              `json:"status"`
	PaidAt    pgtype.Timestamptz `json:"paid_at"`
	FailedAt  pgtype.Timestamptz `json:"failed_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus,
		arg.ID,
		arg.Status,
		arg.PaidAt,
		arg.FailedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateReservationStatus = `-- name: UpdateReservationStatus :exec
UPDATE reservations
SET
    status = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateReservationStatusParams struct {
	ID        int64              `json:"id"`
	Status    int16              `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) error {
	_, err := q.db.Exec(ctx, updateReservationStatus, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}

const updateSectionInventory = `-- name: UpdateSectionInventory :exec
UPDATE event_sections
SET
    reserved_quantity = $2,
    sold_quantity = $3,
    status = $4,
    updated_at = $5
WHERE id = $1
`

type UpdateSectionInventoryParams struct {
	ID               int64              `json:"id"`
	ReservedQuantity int32              `json:"reserved_quantity"`
	SoldQuantity     int32              `json:"sold_quantity"`
	Status           int16              `json:"status"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSectionInventory(ctx context.Context, arg UpdateSectionInventoryParams) error {
	_, err := q.db.Exec(ctx, updateSectionInventory,
		arg.ID,
		arg.ReservedQuantity,
		arg.SoldQuantity,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET
    password_hash = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64              `json:"id"`
	PasswordHash string             `json:"password_hash"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash, arg.UpdatedAt)
	return err
}
