// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error
	ConfirmSectionSale(ctx context.Context, arg ConfirmSectionSaleParams) (EventSection, error)
	CreateAdminAuditLog(ctx context.Context, arg CreateAdminAuditLogParams) (AdminAuditLog, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error)
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrganizer(ctx context.Context, arg CreateOrganizerParams) (Organizer, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePaymentAttempt(ctx context.Context, arg CreatePaymentAttemptParams) (PaymentAttempt, error)
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	CreateSection(ctx context.Context, arg CreateSectionParams) (EventSection, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetActiveReservationByUserAndEvent(ctx context.Context, arg GetActiveReservationByUserAndEventParams) (Reservation, error)
	GetAdminEventByID(ctx context.Context, arg GetAdminEventByIDParams) (GetAdminEventByIDRow, error)
	GetAdminOrderSensitiveByID(ctx context.Context, id int64) (GetAdminOrderSensitiveByIDRow, error)
	GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error)
	GetAdminUserByID(ctx context.Context, id int64) (AdminUser, error)
	GetEventByID(ctx context.Context, id int64) (GetEventByIDRow, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetOrderByID(ctx context.Context, id int64) (Order, error)
	GetOrderByOrderNo(ctx context.Context, orderNo string) (Order, error)
	GetOrganizerByID(ctx context.Context, id int64) (Organizer, error)
	GetPaymentAttemptByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (PaymentAttempt, error)
	GetPaymentAttemptByMerchantTradeNo(ctx context.Context, merchantTradeNo string) (PaymentAttempt, error)
	GetPaymentByPaymentNo(ctx context.Context, paymentNo string) (Payment, error)
	GetReservationByID(ctx context.Context, id int64) (Reservation, error)
	GetReservationByReservationNo(ctx context.Context, reservationNo string) (Reservation, error)
	GetSectionByEventAndID(ctx context.Context, arg GetSectionByEventAndIDParams) (EventSection, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	ListAdminAuditLogs(ctx context.Context, arg ListAdminAuditLogsParams) ([]AdminAuditLog, error)
	ListAdminEventSections(ctx context.Context, arg ListAdminEventSectionsParams) ([]EventSection, error)
	ListAdminEvents(ctx context.Context, organizerID int64) ([]ListAdminEventsRow, error)
	ListAdminOrders(ctx context.Context, arg ListAdminOrdersParams) ([]ListAdminOrdersRow, error)
	ListAdminUsers(ctx context.Context) ([]AdminUser, error)
	ListEvents(ctx context.Context) ([]ListEventsRow, error)
	ListExpiredHoldingReservations(ctx context.Context, arg ListExpiredHoldingReservationsParams) ([]Reservation, error)
	ListExpiredPendingOrders(ctx context.Context, arg ListExpiredPendingOrdersParams) ([]Order, error)
	ListOrdersByUserID(ctx context.Context, userID int64) ([]Order, error)
	ListOrganizers(ctx context.Context) ([]Organizer, error)
	ListPaymentAttemptsByOrderID(ctx context.Context, orderID int64) ([]PaymentAttempt, error)
	ListPaymentsByUserID(ctx context.Context, userID int64) ([]Payment, error)
	ListReservationsByUserID(ctx context.Context, userID int64) ([]Reservation, error)
	ListSectionsByEventID(ctx context.Context, eventID int64) ([]EventSection, error)
	ReleaseSectionInventory(ctx context.Context, arg ReleaseSectionInventoryParams) (EventSection, error)
	ReserveSectionInventory(ctx context.Context, arg ReserveSectionInventoryParams) (EventSection, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdatePaymentAttemptStatus(ctx context.Context, arg UpdatePaymentAttemptStatusParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
	UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) error
	UpdateSectionInventory(ctx context.Context, arg UpdateSectionInventoryParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
