// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    name,
    venue,
    status,
    start_at,
    end_at,
    sale_start_at,
    sale_end_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING
    id,
    name,
    venue,
    status,
    start_at,
    end_at,
    sale_start_at,
    sale_end_at,
    created_at,
    updated_at
`

type CreateEventParams struct {
	Name        string             `json:"name"`
	Venue       string             `json:"venue"`
	Status      int16              `json:"status"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	SaleStartAt pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt   pgtype.Timestamptz `json:"sale_end_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Name,
		arg.Venue,
		arg.Status,
		arg.StartAt,
		arg.EndAt,
		arg.SaleStartAt,
		arg.SaleEndAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Venue,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.SaleStartAt,
		&i.SaleEndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING
    id,
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
`

type CreateOrderParams struct {
	OrderNo       string             `json:"order_no"`
	ReservationID int64              `json:"reservation_id"`
	ReservationNo string             `json:"reservation_no"`
	EventID       int64              `json:"event_id"`
	EventName     string             `json:"event_name"`
	SectionID     int64              `json:"section_id"`
	SectionName   string             `json:"section_name"`
	UserID        int64              `json:"user_id"`
	UserName      string             `json:"user_name"`
	Quantity      int32              `json:"quantity"`
	UnitPrice     int64              `json:"unit_price"`
	TotalAmount   int64              `json:"total_amount"`
	Status        int16              `json:"status"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderNo,
		arg.ReservationID,
		arg.ReservationNo,
		arg.EventID,
		arg.EventName,
		arg.SectionID,
		arg.SectionName,
		arg.UserID,
		arg.UserName,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalAmount,
		arg.Status,
		arg.ExpiresAt,
		arg.PaidAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.ReservationID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    payment_no,
    order_id,
    order_no,
    reservation_id,
    event_id,
    event_name,
    user_id,
    user_name,
    method,
    amount,
    status,
    paid_at,
    failed_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING
    id,
    payment_no,
    order_id,
    order_no,
    reservation_id,
    event_id,
    event_name,
    user_id,
    user_name,
    method,
    amount,
    status,
    paid_at,
    failed_at,
    created_at,
    updated_at
`

type CreatePaymentParams struct {
	PaymentNo     string             `json:"payment_no"`
	OrderID       int64              `json:"order_id"`
	OrderNo       string             `json:"order_no"`
	ReservationID int64              `json:"reservation_id"`
	EventID       int64              `json:"event_id"`
	EventName     string             `json:"event_name"`
	UserID        int64              `json:"user_id"`
	UserName      string             `json:"user_name"`
	Method        string             `json:"method"`
	Amount        int64              `json:"amount"`
	Status        int16              `json:"status"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	FailedAt      pgtype.Timestamptz `json:"failed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.PaymentNo,
		arg.OrderID,
		arg.OrderNo,
		arg.ReservationID,
		arg.EventID,
		arg.EventName,
		arg.UserID,
		arg.UserName,
		arg.Method,
		arg.Amount,
		arg.Status,
		arg.PaidAt,
		arg.FailedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.OrderNo,
		&i.ReservationID,
		&i.EventID,
		&i.EventName,
		&i.UserID,
		&i.UserName,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.PaidAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
`

type CreateReservationParams struct {
	ReservationNo string             `json:"reservation_no"`
	EventID       int64              `json:"event_id"`
	EventName     string             `json:"event_name"`
	SectionID     int64              `json:"section_id"`
	SectionName   string             `json:"section_name"`
	UserID        int64              `json:"user_id"`
	UserName      string             `json:"user_name"`
	Quantity      int32              `json:"quantity"`
	UnitPrice     int64              `json:"unit_price"`
	TotalAmount   int64              `json:"total_amount"`
	Status        int16              `json:"status"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.ReservationNo,
		arg.EventID,
		arg.EventName,
		arg.SectionID,
		arg.SectionName,
		arg.UserID,
		arg.UserName,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalAmount,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSection = `-- name: CreateSection :one
INSERT INTO event_sections (
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING
    id,
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status,
    created_at,
    updated_at
`

type CreateSectionParams struct {
	EventID          int64  `json:"event_id"`
	EventName        string `json:"event_name"`
	SectionName      string `json:"section_name"`
	Price            int64  `json:"price"`
	TotalQuantity    int32  `json:"total_quantity"`
	ReservedQuantity int32  `json:"reserved_quantity"`
	SoldQuantity     int32  `json:"sold_quantity"`
	PurchaseLimit    int32  `json:"purchase_limit"`
	Status           int16  `json:"status"`
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (EventSection, error) {
	row := q.db.QueryRow(ctx, createSection,
		arg.EventID,
		arg.EventName,
		arg.SectionName,
		arg.Price,
		arg.TotalQuantity,
		arg.ReservedQuantity,
		arg.SoldQuantity,
		arg.PurchaseLimit,
		arg.Status,
	)
	var i EventSection
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventName,
		&i.SectionName,
		&i.Price,
		&i.TotalQuantity,
		&i.ReservedQuantity,
		&i.SoldQuantity,
		&i.PurchaseLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT
    id,
    name,
    venue,
    status,
    start_at,
    end_at,
    sale_start_at,
    sale_end_at,
    created_at,
    updated_at
FROM events
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEventByID(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Venue,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.SaleStartAt,
		&i.SaleEndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
    id,
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
FROM orders
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.ReservationID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByOrderNo = `-- name: GetOrderByOrderNo :one
SELECT
    id,
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
FROM orders
WHERE order_no = $1
LIMIT 1
`

func (q *Queries) GetOrderByOrderNo(ctx context.Context, orderNo string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByOrderNo, orderNo)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.ReservationID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByPaymentNo = `-- name: GetPaymentByPaymentNo :one
SELECT
    id,
    payment_no,
    order_id,
    order_no,
    reservation_id,
    event_id,
    event_name,
    user_id,
    user_name,
    method,
    amount,
    status,
    paid_at,
    failed_at,
    created_at,
    updated_at
FROM payments
WHERE payment_no = $1
LIMIT 1
`

func (q *Queries) GetPaymentByPaymentNo(ctx context.Context, paymentNo string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByPaymentNo, paymentNo)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.OrderNo,
		&i.ReservationID,
		&i.EventID,
		&i.EventName,
		&i.UserID,
		&i.UserName,
		&i.Method,
		&i.Amount,
		&i.Status,
		&i.PaidAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetReservationByID(ctx context.Context, id int64) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByID, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationByReservationNo = `-- name: GetReservationByReservationNo :one
SELECT
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE reservation_no = $1
LIMIT 1
`

func (q *Queries) GetReservationByReservationNo(ctx context.Context, reservationNo string) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByReservationNo, reservationNo)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSectionByEventAndID = `-- name: GetSectionByEventAndID :one
SELECT
    id,
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status,
    created_at,
    updated_at
FROM event_sections
WHERE event_id = $1
  AND id = $2
LIMIT 1
`

type GetSectionByEventAndIDParams struct {
	EventID int64 `json:"event_id"`
	ID      int64 `json:"id"`
}

func (q *Queries) GetSectionByEventAndID(ctx context.Context, arg GetSectionByEventAndIDParams) (EventSection, error) {
	row := q.db.QueryRow(ctx, getSectionByEventAndID, arg.EventID, arg.ID)
	var i EventSection
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventName,
		&i.SectionName,
		&i.Price,
		&i.TotalQuantity,
		&i.ReservedQuantity,
		&i.SoldQuantity,
		&i.PurchaseLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT
    id,
    name,
    venue,
    status,
    start_at,
    end_at,
    sale_start_at,
    sale_end_at,
    created_at,
    updated_at
FROM events
ORDER BY id
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Venue,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.SaleStartAt,
			&i.SaleEndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredHoldingReservations = `-- name: ListExpiredHoldingReservations :many
SELECT
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE status = 1
  AND expires_at <= $1
ORDER BY expires_at
LIMIT $2
`

type ListExpiredHoldingReservationsParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListExpiredHoldingReservations(ctx context.Context, arg ListExpiredHoldingReservationsParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listExpiredHoldingReservations, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.ReservationNo,
			&i.EventID,
			&i.EventName,
			&i.SectionID,
			&i.SectionName,
			&i.UserID,
			&i.UserName,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPendingOrders = `-- name: ListExpiredPendingOrders :many
SELECT
    id,
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
FROM orders
WHERE status = 1
  AND expires_at <= $1
ORDER BY expires_at
LIMIT $2
`

type ListExpiredPendingOrdersParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListExpiredPendingOrders(ctx context.Context, arg ListExpiredPendingOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingOrders, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.ReservationID,
			&i.ReservationNo,
			&i.EventID,
			&i.EventName,
			&i.SectionID,
			&i.SectionName,
			&i.UserID,
			&i.UserName,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Status,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT
    id,
    order_no,
    reservation_id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    paid_at,
    created_at,
    updated_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListOrdersByUserID(ctx context.Context, userID int64) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.ReservationID,
			&i.ReservationNo,
			&i.EventID,
			&i.EventName,
			&i.SectionID,
			&i.SectionName,
			&i.UserID,
			&i.UserName,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Status,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByUserID = `-- name: ListReservationsByUserID :many
SELECT
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListReservationsByUserID(ctx context.Context, userID int64) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.ReservationNo,
			&i.EventID,
			&i.EventName,
			&i.SectionID,
			&i.SectionName,
			&i.UserID,
			&i.UserName,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByEventID = `-- name: ListSectionsByEventID :many
SELECT
    id,
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status,
    created_at,
    updated_at
FROM event_sections
WHERE event_id = $1
ORDER BY id
`

func (q *Queries) ListSectionsByEventID(ctx context.Context, eventID int64) ([]EventSection, error) {
	rows, err := q.db.Query(ctx, listSectionsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventSection{}
	for rows.Next() {
		var i EventSection
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventName,
			&i.SectionName,
			&i.Price,
			&i.TotalQuantity,
			&i.ReservedQuantity,
			&i.SoldQuantity,
			&i.PurchaseLimit,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET
    status = $2,
    paid_at = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID        int64              `json:"id"`
	Status    int16              `json:"status"`
	PaidAt    pgtype.Timestamptz `json:"paid_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus,
		arg.ID,
		arg.Status,
		arg.PaidAt,
		arg.UpdatedAt,
	)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments
SET
    status = $2,
    paid_at = $3,
    failed_at = $4,
    updated_at = $5
WHERE id = $1
`

type UpdatePaymentStatusParams struct {
	ID        int64              `json:"id"`
	Status    int16              `json:"status"`
	PaidAt    pgtype.Timestamptz `json:"paid_at"`
	FailedAt  pgtype.Timestamptz `json:"failed_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus,
		arg.ID,
		arg.Status,
		arg.PaidAt,
		arg.FailedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateReservationStatus = `-- name: UpdateReservationStatus :exec
UPDATE reservations
SET
    status = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateReservationStatusParams struct {
	ID        int64              `json:"id"`
	Status    int16              `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) error {
	_, err := q.db.Exec(ctx, updateReservationStatus, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}

const updateSectionInventory = `-- name: UpdateSectionInventory :exec
UPDATE event_sections
SET
    reserved_quantity = $2,
    sold_quantity = $3,
    status = $4,
    updated_at = $5
WHERE id = $1
`

type UpdateSectionInventoryParams struct {
	ID               int64              `json:"id"`
	ReservedQuantity int32              `json:"reserved_quantity"`
	SoldQuantity     int32              `json:"sold_quantity"`
	Status           int16              `json:"status"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSectionInventory(ctx context.Context, arg UpdateSectionInventoryParams) error {
	_, err := q.db.Exec(ctx, updateSectionInventory,
		arg.ID,
		arg.ReservedQuantity,
		arg.SoldQuantity,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}
