// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
`

type CreateReservationParams struct {
	ReservationNo string             `json:"reservation_no"`
	EventID       int64              `json:"event_id"`
	EventName     string             `json:"event_name"`
	SectionID     int64              `json:"section_id"`
	SectionName   string             `json:"section_name"`
	UserID        int64              `json:"user_id"`
	UserName      string             `json:"user_name"`
	Quantity      int32              `json:"quantity"`
	UnitPrice     int64              `json:"unit_price"`
	TotalAmount   int64              `json:"total_amount"`
	Status        int16              `json:"status"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.ReservationNo,
		arg.EventID,
		arg.EventName,
		arg.SectionID,
		arg.SectionName,
		arg.UserID,
		arg.UserName,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalAmount,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveReservationByUserAndEvent = `-- name: GetActiveReservationByUserAndEvent :one
SELECT
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE user_id = $1
  AND event_id = $2
  AND status = 1
  AND expires_at > $3
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetActiveReservationByUserAndEventParams struct {
	UserID    int64              `json:"user_id"`
	EventID   int64              `json:"event_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetActiveReservationByUserAndEvent(ctx context.Context, arg GetActiveReservationByUserAndEventParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, getActiveReservationByUserAndEvent, arg.UserID, arg.EventID, arg.ExpiresAt)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetReservationByID(ctx context.Context, id int64) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByID, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationByIDForUpdate = `-- name: GetReservationByIDForUpdate :one
SELECT
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetReservationByIDForUpdate(ctx context.Context, id int64) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByIDForUpdate, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationByReservationNo = `-- name: GetReservationByReservationNo :one
SELECT
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE reservation_no = $1
LIMIT 1
`

func (q *Queries) GetReservationByReservationNo(ctx context.Context, reservationNo string) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByReservationNo, reservationNo)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationNo,
		&i.EventID,
		&i.EventName,
		&i.SectionID,
		&i.SectionName,
		&i.UserID,
		&i.UserName,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalAmount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredHoldingReservations = `-- name: ListExpiredHoldingReservations :many
SELECT
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE status = 1
  AND expires_at <= $1
ORDER BY expires_at
LIMIT $2
`

type ListExpiredHoldingReservationsParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListExpiredHoldingReservations(ctx context.Context, arg ListExpiredHoldingReservationsParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listExpiredHoldingReservations, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.ReservationNo,
			&i.EventID,
			&i.EventName,
			&i.SectionID,
			&i.SectionName,
			&i.UserID,
			&i.UserName,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByUserID = `-- name: ListReservationsByUserID :many
SELECT
    id,
    reservation_no,
    event_id,
    event_name,
    section_id,
    section_name,
    user_id,
    user_name,
    quantity,
    unit_price,
    total_amount,
    status,
    expires_at,
    created_at,
    updated_at
FROM reservations
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListReservationsByUserID(ctx context.Context, userID int64) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.ReservationNo,
			&i.EventID,
			&i.EventName,
			&i.SectionID,
			&i.SectionName,
			&i.UserID,
			&i.UserName,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalAmount,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReservationStatus = `-- name: UpdateReservationStatus :exec
UPDATE reservations
SET
    status = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateReservationStatusParams struct {
	ID        int64              `json:"id"`
	Status    int16              `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) error {
	_, err := q.db.Exec(ctx, updateReservationStatus, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}

const updateReservationStatusIfCurrent = `-- name: UpdateReservationStatusIfCurrent :execrows
UPDATE reservations
SET
    status = $1,
    updated_at = $2
WHERE id = $3
  AND status = $4
`

type UpdateReservationStatusIfCurrentParams struct {
	Status         int16              `json:"status"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ID             int64              `json:"id"`
	ExpectedStatus int16              `json:"expected_status"`
}

func (q *Queries) UpdateReservationStatusIfCurrent(ctx context.Context, arg UpdateReservationStatusIfCurrentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateReservationStatusIfCurrent,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
