// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: section.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmSectionSale = `-- name: ConfirmSectionSale :one
UPDATE event_sections
SET
    reserved_quantity = reserved_quantity - $1::integer,
    sold_quantity = sold_quantity + $1::integer,
    status = CASE
        WHEN total_quantity - (reserved_quantity - $1::integer) - (sold_quantity + $1::integer) = 0 THEN 3
        ELSE status
    END,
    updated_at = $2
WHERE event_id = $3
  AND id = $4
  AND $1::integer > 0
  AND reserved_quantity >= $1::integer
RETURNING
    id,
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status,
    created_at,
    updated_at
`

type ConfirmSectionSaleParams struct {
	Quantity  int32              `json:"quantity"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	EventID   int64              `json:"event_id"`
	ID        int64              `json:"id"`
}

func (q *Queries) ConfirmSectionSale(ctx context.Context, arg ConfirmSectionSaleParams) (EventSection, error) {
	row := q.db.QueryRow(ctx, confirmSectionSale,
		arg.Quantity,
		arg.UpdatedAt,
		arg.EventID,
		arg.ID,
	)
	var i EventSection
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventName,
		&i.SectionName,
		&i.Price,
		&i.TotalQuantity,
		&i.ReservedQuantity,
		&i.SoldQuantity,
		&i.PurchaseLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSection = `-- name: CreateSection :one
INSERT INTO event_sections (
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING
    id,
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status,
    created_at,
    updated_at
`

type CreateSectionParams struct {
	EventID          int64  `json:"event_id"`
	EventName        string `json:"event_name"`
	SectionName      string `json:"section_name"`
	Price            int64  `json:"price"`
	TotalQuantity    int32  `json:"total_quantity"`
	ReservedQuantity int32  `json:"reserved_quantity"`
	SoldQuantity     int32  `json:"sold_quantity"`
	PurchaseLimit    int32  `json:"purchase_limit"`
	Status           int16  `json:"status"`
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (EventSection, error) {
	row := q.db.QueryRow(ctx, createSection,
		arg.EventID,
		arg.EventName,
		arg.SectionName,
		arg.Price,
		arg.TotalQuantity,
		arg.ReservedQuantity,
		arg.SoldQuantity,
		arg.PurchaseLimit,
		arg.Status,
	)
	var i EventSection
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventName,
		&i.SectionName,
		&i.Price,
		&i.TotalQuantity,
		&i.ReservedQuantity,
		&i.SoldQuantity,
		&i.PurchaseLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSectionByEventAndID = `-- name: GetSectionByEventAndID :one
SELECT
    id,
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status,
    created_at,
    updated_at
FROM event_sections
WHERE event_id = $1
  AND id = $2
LIMIT 1
`

type GetSectionByEventAndIDParams struct {
	EventID int64 `json:"event_id"`
	ID      int64 `json:"id"`
}

func (q *Queries) GetSectionByEventAndID(ctx context.Context, arg GetSectionByEventAndIDParams) (EventSection, error) {
	row := q.db.QueryRow(ctx, getSectionByEventAndID, arg.EventID, arg.ID)
	var i EventSection
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventName,
		&i.SectionName,
		&i.Price,
		&i.TotalQuantity,
		&i.ReservedQuantity,
		&i.SoldQuantity,
		&i.PurchaseLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminEventSections = `-- name: ListAdminEventSections :many
SELECT
    s.id,
    s.event_id,
    s.event_name,
    s.section_name,
    s.price,
    s.total_quantity,
    s.reserved_quantity,
    s.sold_quantity,
    s.purchase_limit,
    s.status,
    s.created_at,
    s.updated_at
FROM event_sections s
JOIN events e ON e.id = s.event_id
WHERE s.event_id = $1
  AND (
      $2::bigint = 0
      OR e.organizer_id = $2
  )
ORDER BY s.id
`

type ListAdminEventSectionsParams struct {
	EventID     int64 `json:"event_id"`
	OrganizerID int64 `json:"organizer_id"`
}

func (q *Queries) ListAdminEventSections(ctx context.Context, arg ListAdminEventSectionsParams) ([]EventSection, error) {
	rows, err := q.db.Query(ctx, listAdminEventSections, arg.EventID, arg.OrganizerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventSection{}
	for rows.Next() {
		var i EventSection
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventName,
			&i.SectionName,
			&i.Price,
			&i.TotalQuantity,
			&i.ReservedQuantity,
			&i.SoldQuantity,
			&i.PurchaseLimit,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByEventID = `-- name: ListSectionsByEventID :many
SELECT
    id,
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status,
    created_at,
    updated_at
FROM event_sections
WHERE event_id = $1
ORDER BY id
`

func (q *Queries) ListSectionsByEventID(ctx context.Context, eventID int64) ([]EventSection, error) {
	rows, err := q.db.Query(ctx, listSectionsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventSection{}
	for rows.Next() {
		var i EventSection
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventName,
			&i.SectionName,
			&i.Price,
			&i.TotalQuantity,
			&i.ReservedQuantity,
			&i.SoldQuantity,
			&i.PurchaseLimit,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseSectionInventory = `-- name: ReleaseSectionInventory :one
UPDATE event_sections
SET
    reserved_quantity = reserved_quantity - $1::integer,
    status = CASE
        WHEN status = 3 AND total_quantity - (reserved_quantity - $1::integer) - sold_quantity > 0 THEN 1
        ELSE status
    END,
    updated_at = $2
WHERE event_id = $3
  AND id = $4
  AND $1::integer > 0
  AND reserved_quantity >= $1::integer
RETURNING
    id,
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status,
    created_at,
    updated_at
`

type ReleaseSectionInventoryParams struct {
	Quantity  int32              `json:"quantity"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	EventID   int64              `json:"event_id"`
	ID        int64              `json:"id"`
}

func (q *Queries) ReleaseSectionInventory(ctx context.Context, arg ReleaseSectionInventoryParams) (EventSection, error) {
	row := q.db.QueryRow(ctx, releaseSectionInventory,
		arg.Quantity,
		arg.UpdatedAt,
		arg.EventID,
		arg.ID,
	)
	var i EventSection
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventName,
		&i.SectionName,
		&i.Price,
		&i.TotalQuantity,
		&i.ReservedQuantity,
		&i.SoldQuantity,
		&i.PurchaseLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveSectionInventory = `-- name: ReserveSectionInventory :one
UPDATE event_sections
SET
    reserved_quantity = reserved_quantity + $1::integer,
    updated_at = $2
WHERE event_id = $3
  AND id = $4
  AND status = 1
  AND $1::integer > 0
  AND (purchase_limit = 0 OR $1::integer <= purchase_limit)
  AND reserved_quantity + sold_quantity + $1::integer <= total_quantity
RETURNING
    id,
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status,
    created_at,
    updated_at
`

type ReserveSectionInventoryParams struct {
	Quantity  int32              `json:"quantity"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	EventID   int64              `json:"event_id"`
	ID        int64              `json:"id"`
}

func (q *Queries) ReserveSectionInventory(ctx context.Context, arg ReserveSectionInventoryParams) (EventSection, error) {
	row := q.db.QueryRow(ctx, reserveSectionInventory,
		arg.Quantity,
		arg.UpdatedAt,
		arg.EventID,
		arg.ID,
	)
	var i EventSection
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventName,
		&i.SectionName,
		&i.Price,
		&i.TotalQuantity,
		&i.ReservedQuantity,
		&i.SoldQuantity,
		&i.PurchaseLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSection = `-- name: UpdateSection :one
UPDATE event_sections
SET
    section_name = $3,
    price = $4,
    total_quantity = $5,
    purchase_limit = $6,
    status = $7,
    updated_at = $8
WHERE event_id = $1
  AND id = $2
RETURNING
    id,
    event_id,
    event_name,
    section_name,
    price,
    total_quantity,
    reserved_quantity,
    sold_quantity,
    purchase_limit,
    status,
    created_at,
    updated_at
`

type UpdateSectionParams struct {
	EventID       int64              `json:"event_id"`
	ID            int64              `json:"id"`
	SectionName   string             `json:"section_name"`
	Price         int64              `json:"price"`
	TotalQuantity int32              `json:"total_quantity"`
	PurchaseLimit int32              `json:"purchase_limit"`
	Status        int16              `json:"status"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSection(ctx context.Context, arg UpdateSectionParams) (EventSection, error) {
	row := q.db.QueryRow(ctx, updateSection,
		arg.EventID,
		arg.ID,
		arg.SectionName,
		arg.Price,
		arg.TotalQuantity,
		arg.PurchaseLimit,
		arg.Status,
		arg.UpdatedAt,
	)
	var i EventSection
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventName,
		&i.SectionName,
		&i.Price,
		&i.TotalQuantity,
		&i.ReservedQuantity,
		&i.SoldQuantity,
		&i.PurchaseLimit,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSectionInventory = `-- name: UpdateSectionInventory :exec
UPDATE event_sections
SET
    reserved_quantity = $2,
    sold_quantity = $3,
    status = $4,
    updated_at = $5
WHERE id = $1
`

type UpdateSectionInventoryParams struct {
	ID               int64              `json:"id"`
	ReservedQuantity int32              `json:"reserved_quantity"`
	SoldQuantity     int32              `json:"sold_quantity"`
	Status           int16              `json:"status"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSectionInventory(ctx context.Context, arg UpdateSectionInventoryParams) error {
	_, err := q.db.Exec(ctx, updateSectionInventory,
		arg.ID,
		arg.ReservedQuantity,
		arg.SoldQuantity,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}
