app.store=postgres
queue.store=redis
postgres.dsn=postgres://postgres:postgres@localhost:5432/buy_ticket?sslmode=disable
postgres.pool.maxIdleConns=5
postgres.pool.maxOpenConns=20
postgres.connMaxIdleTime=30m
postgres.connMaxLifetime=2h
redis.addr=localhost:6379
redis.db=0
redis.password=
payment.mock.merchant_id=TEST_MERCHANT
payment.mock.hash_key=TEST_SECRET
payment.mock.hash_iv=TEST_HASH_IV
